### ISSUE TITLE
The configuration 'spring.json.key.default.type' was supplied but isn't a known config.

### ISSUE THREAD

**Issue by tigerinus** [spring-projects/spring-kafka#2323] opened 2022-07-01 13:14 UTC
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.6

**Describe the bug**

When configurating `DefaultKafkaConsumerFactory`, it says `The configuration 'spring.json.key.default.type' was supplied but isn't a known config.` 

**To Reproduce**

Following https://docs.spring.io/spring-kafka/docs/latest-ga/reference/html/#error-handling-deserializer to configure `DefaultKafkaConsumerFactory` like 

(copied from official doc)
```java
props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer.class);
props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer.class);
props.put(ErrorHandlingDeserializer.KEY_DESERIALIZER_CLASS, JsonDeserializer.class);
props.put(JsonDeserializer.KEY_DEFAULT_TYPE, "com.example.MyKey")
props.put(ErrorHandlingDeserializer.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class.getName());
props.put(JsonDeserializer.VALUE_DEFAULT_TYPE, "com.example.MyValue")  // <-- this line
props.put(JsonDeserializer.TRUSTED_PACKAGES, "com.example")
return new DefaultKafkaConsumerFactory<>(props);
```

the run the consumer.

The log would report

```
2022-07-01 09:02:19.345  WARN 6765 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'spring.json.key.default.type' was supplied but isn't a known config.
```

**Expected behavior**

The behavior should match what's described in the doc. Either doc should be updated or the behavior should be fixed.

**Comment by artembilan** [comment] 2022-07-01 16:12
The `ConsumerConfig` is out of this project scope. It is a part of Kafka Client project.
They log that warn just because it is not a standard consumer property.
We believe that this has to be changed to the `info` level, but that's already outside of our project scope.

The configuration and docs are correct and confirmed with many field testing and production.

Such a warning better to just ignore.
As far as I know the Kafka Client even warn for Confluent standard Avro properties...

See more info here: https://issues.apache.org/jira/browse/KAFKA-6793

Closed as `Works as Designed`

**Closed by artembilan** 2022-07-01 16:12 UTC
Labels: type: bug, status: waiting-for-triage
