### ISSUE TITLE
Spring Boot with Kafka Template with supplied tags provider breaks spring_kafka_template metric

### ISSUE THREAD

**Issue by HStoyanov-augglobal** [spring-projects/spring-kafka#3275] opened 2024-05-23 13:41 UTC
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.1 And some other versions

**Describe the bug**

I have metrics and prometheus enabled, I am creating my own KafkaTemplate and setting a `micrometerTagsProvider` for it. And at that point the `spring_kafka_template_...` metrics all break, they stop, value at 0, the given tags are not shown. It doesn't matter what tag name or value i provide, or how many, behavior is the same. However, if i provide an **empty Map**, the metric will start working again.

KafkaTemplate also support adding static tags via `KafkaTemplate#setMicrometerTags(Map)`. This always works and doesn't break the metric. Metric will show these static tags in all cases (even if micrometerTagsProvider is used).

**To Reproduce**

1) KafkaTemplate<String, String> template = new KafkaTemplate<>(producerFactory);
2) template.setMicrometerTagsProvider(producerRecord -> Map.of("topic", producerRecord.topic()));
3) `spring_kafka_template_...` break, value showing 0, tags not present ex:

`spring_kafka_template_seconds_sum{exception="none",name="testKafkaTemplateWithTagsProvider",result="success",} 0`

**Expected behavior**

`spring_kafka_template_seconds_sum{topic=someTopic, exception="none",name="testKafkaTemplateWithTagsProvider",result="success",} 1.306612559`

**Sample**

You can run a small project to test it yourself if you have access to your own kafka: https://github.com/HStoyanov-augglobal/kafka-metrics-springboot-bug-report/tree/main

Metrics available at `http://localhost:8080/actuator/prometheus`

See this code in particular where `micrometerTagsProvider` is specified, along with 3 cases to experiment with: https://github.com/HStoyanov-augglobal/kafka-metrics-springboot-bug-report/blob/main/src/main/java/bugreport/BugReportApplication.java#L33-L47

**Comment by sobychacko** [comment] 2024-05-24 14:14
@HStoyanov-augglobal The latest version in `3.1.x` is `3.1.5`. Could you upgrade and see if the problem persists? Also, if the problem is still there, can you update your app so we can easily run it out of the box and see the issue? It is not clear how to run the app against a standalone cluster and see the issue. Please provide instructions on how to run the app without making any code changes, Prometheus setup, etc. Thanks!

**Comment by HStoyanov-augglobal** [comment] 2024-05-25 15:50
@sobychacko Updated project to spring kafka `3.1.5`, same behavior:

```
# HELP spring_kafka_template_seconds_max KafkaTemplate Timer
# TYPE spring_kafka_template_seconds_max gauge
spring_kafka_template_seconds_max{exception="none",name="testKafkaTemplateWithTagsProvider",result="success",} 0.0
spring_kafka_template_seconds_max{exception="none",name="testKafkaTemplateWithoutTagsProvider",result="success",} 2.679072054
# HELP spring_kafka_template_seconds KafkaTemplate Timer
# TYPE spring_kafka_template_seconds summary
spring_kafka_template_seconds_count{exception="none",name="testKafkaTemplateWithTagsProvider",result="success",} 0.0
spring_kafka_template_seconds_sum{exception="none",name="testKafkaTemplateWithTagsProvider",result="success",} 0.0
spring_kafka_template_seconds_count{exception="none",name="testKafkaTemplateWithoutTagsProvider",result="success",} 9.0
spring_kafka_template_seconds_sum{exception="none",name="testKafkaTemplateWithoutTagsProvider",result="success",} 3.726230418
```
Those are metrics for 2 kafka templates running at the same time. One is with tags provider, other without. The one with the tags provider still has 0 value and doesn't show the tag.

To run, see README.md. Synops:

```bash
mvn package
export bugreport_bootstrapServers='host:port' bugreport_topic='metrics-bug-report-test' && java -jar target/metrics-bug-1.0.0-SNAPSHOT.jar
```

* With kafka with SSL:

```bash
mvn package
export bugreport_bootstrapServers='host:port' bugreport_topic='metrics-bug-report-test-topic' bugreport_sslSecurityProtocol='SSL' bugreport_sslKeyPassword='YOUR KEY PASS' bugreport_sslKeystorePath='path/to/kafka.keystore.jks' bugreport_sslKeystorePassword='YOUR KEYSTORE PASS' bugreport_sslTruststorePath='/path/to/kafka.truststore.jks' bugreport_sslTruststorePassword='YOUR TRUSTSTORE PASS' && java -jar target/metrics-bug-1.0.0-SNAPSHOT.jar
```

**Comment by sobychacko** [comment] 2024-05-30 18:49
@HStoyanov-augglobal We were able to look at this issue. We are seeing the right metrics data if you use the regular `metrics` actuator endpoint.

To enable metrics:
```
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=metrics
```
We also need to remove the `micrometer-registry-prometheus` dependency in the pom. 

Then we see this upon invoking the metrics endpoint:

```
curl http://localhost:8080/actuator/metrics/spring.kafka.template | jq
```
```
{
  "name": "spring.kafka.template",
  "description": "KafkaTemplate Timer",
  "baseUnit": "seconds",
  "measurements": [
    {
      "statistic": "COUNT",
      "value": 1
    },
    {
      "statistic": "TOTAL_TIME",
      "value": 0.153589667
    },
    {
      "statistic": "MAX",
      "value": 0.153589667
    }
  ],
  "availableTags": [
    {
      "tag": "result",
      "values": [
        "success"
      ]
    },
    {
      "tag": "exception",
      "values": [
        "none"
      ]
    },
    {
      "tag": "name",
      "values": [
        "testKafkaTemplateWithTagsProvider"
      ]
    },
    {
      "tag": "topic",
      "values": [
        "metrics-bug-report-test-topic"
      ]
    }
  ]
}
````

It turns out that Prometheus is having some issues processing any dynamic tag that you have in the application, so this doesn't work:
```
template.setMicrometerTagsProvider(producerRecord -> Map.of("topic", producerRecord.topic()));
```
The following works with Prometheus, but this may not be what you are looking for:
```
template.setMicrometerTags(Map.of("topic", "metrics-bug-report-test-topic"));
```

Any static values provided as tags are processed when the application starts, whereas the dynamic tag values are only processed when the message is sent from the `ProducerRecord.` Prometheus is having trouble getting this data. 

With the `metrics` endpoint, the `setMicrometerTagsProvider` works as expected. 

When Prometheus is used, the meters are still present in the registry from Spring Kafka's perspective, as shown below.

![image](https://github.com/spring-projects/spring-kafka/assets/827682/54670576-ad58-420a-87b5-aceaa2efd6c6)

However, when calling via the endpoint, it only sees the default meter created at the startup, not the one with the dynamic tag present.

![image](https://github.com/spring-projects/spring-kafka/assets/827682/3490808a-d885-4fe4-b149-193fda7cc108)

Since it looks like it is not a problem from the Spring Kafka framework, we suggest reaching out to the Prometheus team for further troubleshooting. Or use a different metrics registry.

**Comment by sobychacko** [comment] 2024-06-10 17:53
@HStoyanov-augglobal Any updates on this issue?

**Comment by HStoyanov-augglobal** [comment] 2024-06-11 04:52
Forwarded it to micrometer team as suggested. No response from them yet.

**Comment by sobychacko** [comment] 2024-06-14 17:46
Thanks for the update. Closing the issue as there is nothing further to do with the current state. Please feel free to re-open if there is a need.

**Closed by sobychacko** 2024-06-14 17:46 UTC
Labels: question

**Comment by cutemic** [comment] 2024-07-08 07:12
I ran into the same issue today. After some investigation I found that Spring Kafka would register a timer when initializting KafkaTemplate, but at that time there is no ProducerRecord so it won't add custom tags. However, Prometheus requires meters with the same name to have the same set of tags, and so later when a new timer is created with the same name but with the custom tag added, it will fail to be registered.
The workaround I used is to set empty custom tags for the default timer as well using setMicrometerTags().
