### ISSUE TITLE
Spring Boot 3.2.0 > java.lang.NullPointerException: Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null

### ISSUE THREAD

**Issue by Mandroide** [spring-projects/spring-kafka#2914] opened 2023-11-24 20:39 UTC
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
3.1.0

**Describe the bug**
I have the following test class

```java
import org.springframework.kafka.test.context.EmbeddedKafka;
import org.springframework.test.annotation.DirtiesContext;

@DirtiesContext
@EmbeddedKafka(
                partitions = 1,
                brokerProperties = {"listeners=PLAINTEXT://localhost:9092", "port=9092"},
                topics = {"${kafka.app.topics.request}", "${kafka.app.topics.response}"}
)
@SpringBootTest
@ActiveProfiles({"test"})
class AppTest {
...MockBeans of my Project
}
```

When I upgraded to Spring Boot 3.2.0, it throws the following Exception:

java.lang.NullPointerException: Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null

**To Reproduce**

1. Upgrade from Spring Boot 3.1.x to Spring Boot 3.2.0
2. Have a template like the one formerly showed.
3. Run the test

**Expected behavior**

java.lang.NullPointerException: Cannot invoke "kafka.raft.KafkaRaftManager.apiVersions()" because the return value of "kafka.server.SharedServer.raftManager()" is null

**Comment by garyrussell** [comment] 2023-11-27 15:56
Please show your POM and/or dependency tree - you must let Boot manage the version for all Kafka jars so that they are all compatible with each other.

**Comment by artembilan** [comment] 2023-12-01 16:17
You can just do for now `@EmbeddedKafka(kraft = false)`.
We will look deeper a bit later to determine what is going on.

**Comment by charboubmustapha** [comment] 2023-12-01 16:26
> You can just do for now `@EmbeddedKafka(kraft = false)`. We will look deeper a bit later to determine what is going on.

Yep this what i just figured out , i can confirme that passing kraft to false fixed the issue .
Thanks

**Comment by sobychacko** [comment] 2023-12-01 20:16
@charboubmustapha @Mandroide I am trying the following simple test with Boot `3.2.0` and Spring Kafka `3.1.0` and running the test doesn't throw an exception.
```
@DirtiesContext
@EmbeddedKafka(
		partitions = 1,
		brokerProperties = {"listeners=PLAINTEXT://localhost:9092", "port=9092"},
		topics = "my-topic"
)
@SpringBootTest
class Gh2914ApplicationTests {

	@Autowired
	KafkaTemplate<String, String> kafkaTemplate;

	@Test
	void contextLoads() {
		kafkaTemplate.send("my-topic", "data");
	}
}
```
How can we reproduce the issue? It would be great if you could provide a simple app where we can triage the issue. Thanks!

**Comment by sobychacko** [comment] 2023-12-06 15:09
@charboubmustapha @Mandroide Any updates?

**Comment by charboubmustapha** [comment] 2023-12-08 11:16
@sobychacko i can confirm that problem stil there , i was not able to create the topic without disabling kraft.
 i will try to create a simple example to reproduce .
btw this is the stacktrace of the exception .

`at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic topic1 not present in metadata after 60000 ms.
`

**Comment by charboubmustapha** [comment] 2023-12-08 15:11
> 3.1.0

yep the problem doesn't exist in this version 3.1.0 but with 3.2.0

**Comment by sobychacko** [comment] 2023-12-08 15:22
@charboubmustapha I could not reproduce it on my end with the latest snapshot. Are you using Windows, as @artembilan mentioned?

**Comment by charboubmustapha** [comment] 2023-12-08 15:54
@sobychacko @artembilan please find in attachement example to reproduce .

[kraft.zip](https://github.com/spring-projects/spring-kafka/files/13618456/kraft.zip)
I'm using a mac M1 , disabling kraft in test fix the issue

**Comment by sobychacko** [comment] 2023-12-08 21:02
@charboubmustapha Thanks for the sample app.  In your test method, you use `EmbeddedKafkaBroker` as below. 
```
@EmbeddedKafka(topics = "topic1",partitions = 1, brokerProperties = {"listeners=PLAINTEXT://localhost:9092", "port=9092"})
```

However, a restriction in Kafka's `kraft` testing support does not allow us to customize random ports. Please look at this related [issue](https://github.com/spring-projects/spring-kafka/issues/2916) for details. Because of this limitation, you cannot specify hard-coded `port` or `listeners` properties as you have in your configuration. Kafka's `kraft` test support will create a random port for you. This is the problem that you are running into. You expect embedded Kafka to be available at `localhost:9092`, but it is not creating it for you. In `zk` mode, you can provide this custom port information, so the test passes when you have `kraft` mode set to `false.` 

To work around this issue, use the `EmbeddedKafka` without the broker properties you provide.
```
@EmbeddedKafka(topics = "topic1",partitions = 1)
```

And then later on, when you use `BOOTSTRAP_SERVERS_CONFIG`, in your `getConfiguration` method, instead of setting this to `localhost:9092`, do the following instead.
```
properties.put(BOOTSTRAP_SERVERS_CONFIG, System.getProperty("spring.kafka.bootstrap-servers"));
```
We need to use `System.getProperty` because you are using `SpringJUnitConfig.` If you had created a `SpringBootTest` instead, we could have autowired `KafkaProperties` directly and accessed the `bootstrap-server` properties. 

Since it is a limitation of the Kafka client, and there is little we can do here, I will close this issue. Feel free to re-open if there is any new development. When Kafka testing support for `kraft` addresses this solution, we will fix it on the `EmbeddedKafkaKraftBroker` in Spring for Apache Kafka. Thanks!

**Closed** 2023-12-08 21:05 UTC
Labels: status: waiting for reporter

**Comment by garyrussell** [comment] 2023-12-08 21:42
For the record, it is not good practice to hard code the port used in tests. It can cause conflicts when multiple test run concurrently on the same machine.
