### ISSUE TITLE
Consider removing @DirtiesContext necessity for @EmbeddedKafka

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-kafka#2264] opened 2022-05-06 10:22 UTC
**Expected Behavior**

Hello,

At the moment we are testing a Spring Boot application with en embedded Kafka broker, as described in the documentation. We are using JUnit 5. Our usual test class is 

```java
@DirtiesContext
@SpringBootTest(...)
@EmbeddedKafka(...)
class MyTest {
 ...
}
```

As described in the documentation we need to add `@DirtiesContext` on the class specifically for the Kafka broker. This feels a bit wrong, as it resets the whole test application context, and not only the Kafka broker. It is also a pain point for the tests' execution time, as resetting and recreating the context for multiple test classes may be long.

It would be great if the behavior would be similar to the one found for instance with [WebTestClientContextCustomizer](https://github.com/spring-projects/spring-boot/blob/fbe614a61bb55bf1f0ca917600494438e5551a02/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/reactive/server/WebTestClientContextCustomizer.java), which does not need to have a context reset.

**Comment by artembilan** [comment] 2022-05-06 14:40
I'm not sure what documentation are you talking about. Even if we have a `@DirtiesContext` in the [sample](https://docs.spring.io/spring-kafka/docs/current/reference/html/#using-the-same-brokers-for-multiple-test-classes) over there, it doesn't say that  `@DirtiesContext` is mandatory.

There is indeed an `EmbeddedKafkaContextCustomizer` which does the trick adding an `EmbeddedKafkaBroker` bean into the application context and ensuring that cache key is consistent with its `hashCode()` impl.
but of course all your tests must have the same `@EmbeddedKafka` definition. As long as you have some attributes different, the cache key is violated and context is not considered for reuse.

**Comment by celcius112** [comment] 2022-05-06 14:57
Actually from a previous [issue](https://github.com/spring-projects/spring-kafka/issues/1805) I opened there are some cases where the broker is not properly destroyed/disposed and the port is not released. 

It is true however that the documentation does not explicitly ask for this annotation. That's my bad.

As such, maybe we could change this issue to include my initial problem with the port not being released when the test context is not reused.

**Comment by artembilan** [comment] 2022-05-06 15:04
If no `@DirtiesContext`, the application context is cached with all its beans, including that Kafka broker is its obtained port.
As long as you'd like to reuse the context and therefore that embedded Kafka broker, you need to ensure that all the variables in the cache key equation are the same.
Otherwise you cache for nothing therefore better to have `@DirtiesContext` to clean up the cache and that port in the end.
That's kinda fundamental rules of Spring Testing Framework: not sure why you are asking to do something in this project, when the scope of the problem is out of Apache Kafka by itself: https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#testcontext-ctx-management-caching

**Comment by celcius112** [comment] 2022-05-06 16:39
This next question might be more of a spring-framework question, but isn't there a way to close the broker when the cache is refreshed in order to free up the port ?

For instance in this exemple application: 
[test-kafka-broker.zip](https://github.com/spring-projects/spring-kafka/files/8642166/test-kafka-broker.zip)
I have two test classes
```
@SpringBootTest
@EmbeddedKafka(partitions = 1, brokerProperties = "listeners=PLAINTEXT://localhost:9092")
abstract class BaseTest {
}

class Tests1 extends BaseTest {

	@Test
	void contextLoads() {
	}
}

class Tests2 extends BaseTest {

	@Test
	void contextLoads() {
	}

	@TestConfiguration
	static class Config {
		@Bean
		public String bean() {
			return "";
		}
	}
}
```
The second tests "dirties" the context by adding a bean. Tests1 is launched first and Tests2 second. Tests2 will try to recreate the broker, but will fail because the port was not freed up.

Is there a better way than apply a `@DirtiesContext` on each test classes ? For instance "caching" the broker, or preventing this error if the port is already allocated. For code base with hundreds of test a `@DirtiesContext` applied on every class is a pain point.

**Comment by artembilan** [comment] 2022-05-06 17:05
What you are asking is more like a Kafka broker outside of test suite scope.
I guess there are several approaches to consider instead of `@EmbeddedKafka`:

1. Use external Kafka broker which is not dependent on your project.
2. Use Testcontainers with its `reuse` option.
3. Use a static initialization trick we explain in the docs: https://docs.spring.io/spring-kafka/docs/current/reference/html/#using-the-same-brokers-for-multiple-test-classes

The point is that you try to abuse Spring Testing Framework with the feature which is out of its scope: as long as the cache key is not the same, the application context must be stopped and cleared. Otherwise `port already in use` problem.

**Comment by celcius112** [comment] 2022-05-06 18:50
Thank you for the careful and detailed explanation, I found my solution with the third proposition.

For future reference, here's what I ended up doing: 

1. I created a JUnit 5 extension that initializes the kafka broker. This initialization is done only once per test suite, and only if at least one test uses the extension, so that if we launch tests that do not require a spring context we do not create the kafka broker for nothing: 
```
public class KafkaBrokerExtension implements BeforeAllCallback {

  private static EmbeddedKafkaBroker embeddedKafkaBroker;

  static Optional<EmbeddedKafkaBroker> getEmbeddedKafkaBroker() {
    return Optional.ofNullable(embeddedKafkaBroker);
  }

  @Override
  public void beforeAll(ExtensionContext extensionContext) {
    if (embeddedKafkaBroker == null) {
      embeddedKafkaBroker = buildEmbeddedKafkaBroker();
    }
  }

  private static EmbeddedKafkaBroker buildEmbeddedKafkaBroker() {
    EmbeddedKafkaBroker embeddedKafkaBroker = new EmbeddedKafkaBroker(1, false, 1)
        .brokerProperties(Map.of("listeners", "PLAINTEXT://localhost:9092"));
    embeddedKafkaBroker.afterPropertiesSet();
    return embeddedKafkaBroker;
  }
}
```

2. I also created a `TestExecutionListener` (see https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom) that destroys the broker, if it exists, when all tests are executed:
```
public class EmbeddedKafkaBrokerDestroyer implements TestExecutionListener {
  @Override
  public void testPlanExecutionFinished(TestPlan testPlan) {
    KafkaBrokerExtension.getEmbeddedKafkaBroker().ifPresent(EmbeddedKafkaBroker::destroy);
  }
}
```

It's not a perfect solution (I don't like static initializers) but we improved the build time by 20%.

**Comment by artembilan** [comment] 2022-05-06 19:08
OK. That also is possible.

I wonder if we are good so far and can already close the issue since there is, well, no issue with the library.

**Comment by celcius112** [comment] 2022-05-09 07:32
Well I am still wondering wether

**Comment by celcius112** [comment] 2022-05-09 07:48
Well I am still wondering why we would use the spring test context lifecycle for initializing the broker when using JUnit 5. Couldn't we have an option to simply use the JUnit 5 test lifecycle ? It might be enough for many project.

I saw several projects that need to add `@DirtiesContext` everywhere because of one configuration that invalidates the cache only once. I am pretty sure that using JUnit 5 test lifecycle would be a benefit for many.

**Comment by artembilan** [comment] 2022-05-09 14:02
The `EmbeddedKafkaBroker` is Spring feature, so it is not a surprise that it is advertised to be used with Spring test context.
Sure! You can implement your own JUnit 5 extension like you do for that `testPlanExecutionStarted()/testPlanExecutionFinished()`.

I'm not sure that it would be good to have such an impl as an out-of-the-box feature in this project, since this kind of listeners is registered only once for the whole test plan and some of your tests might not be interested in Kafka at all.

**Comment by celcius112** [comment] 2022-05-10 10:27
Using a JUnit 5 extension (and not `testPlanExecutionStarted`) we can use it only on the tests requiring a broker. In most cases I think we do not need to use spring test context for this. 

Well anyway if anybody preferes to use a simple JUnit 5 extension the code found above should do the trick :)

**Closed** 2022-05-10 10:27 UTC
Labels: type: enhancement, status: waiting for reporter

**Comment by artembilan** [comment] 2022-05-10 14:09
Well, then extension you suggest is not consistent: it may start the broker in a first test, but it is not going to be stopped until the end of the plan.
When only that first class is interested in such a broker.
I know that my `testPlanExecutionStarted()`  is too drastic, but at least it is very clean what is going on around the whole test plan.

This Embedded Kafka was really designed for individual test cases, for different Kafka environment, different number of brokers etc.
What you are talking about is more like a single Kafka instance which is better to manage outside of the project test plan.
Your suggestion is just a bit of an anti-pattern for Unit paradigms.

**Comment by cderianb** [comment] 2022-07-04 04:54
@celcius112 hello, i tried to avoid `@DirtiestContext` also and define the broker manually. it works fine
but when i tried to do `mvn install` somehow it failed saying 
`Connection to node 0 (localhost/127.0.0.1:44697) could not be established. Broker may not be available.` 
but when i changed to port 9092, it said the port already in use

how do you manage to establish your kafka connection ?
