### ISSUE TITLE
Getting org.apache.kafka.common.errors.TimeoutException after upgrading to spring 3.4.0

### ISSUE THREAD

**Issue by Casper-dss** [spring-projects/spring-kafka#3649] opened 2024-11-25 19:57 UTC
After upgrading to spring 3.4.0 we are getting this error

org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeConsumerGroups(api=DESCRIBE_GROUPS)

and this is the code producing the error

`try (var adminClient = AdminClient.create(getAdminClientCpnmfiguration())) {
     var remoteGroupDescription = adminClient.describeConsumerGroups(List.of(groupId)).all().get().get(groupId);
}`

the stack trace looks like this.
```
org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeConsumerGroups(api=DESCRIBE_GROUPS)
Wrapped by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeConsumerGroups(api=DESCRIBE_GROUPS)
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at dk.domstol.spring.kafka.health.KafkaHealth.health(KafkaHealth.java:63)
	at o.s.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at dk.domstol.spring.kafka.health.KafkaHealth.getHealth(KafkaHealth.java:45)
	at o.s.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:94)
	at o.s.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:47)
	at o.s.boot.actuate.health.HealthEndpointSupport.getLoggedHealth(HealthEndpointSupport.java:172)
	at o.s.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:145)
	at o.s.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:156)
	at o.s.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:141)
	at o.s.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:110)
	at o.s.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:78)
	at o.s.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:80)
	at o.s.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:75)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
	at o.s.b.a.e.i.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74)
	at o.s.b.a.e.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at o.s.b.a.e.w.s.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:327)
	at o.s.b.a.e.w.s.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:434)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at o.s.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at o.s.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:986)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:891)
	at o.s.w.s.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at o.s.b.a.a.web.servlet.CompositeHandlerAdapter.handle(CompositeHandlerAdapter.java:58)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at o.s.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at o.s.s.w.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
	at o.s.s.w.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
	at o.s.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
	at o.s.s.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:101)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at o.s.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
	at o.s.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.w.a.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.w.s.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.o.s.r.w.a.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:128)
	at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at o.s.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at o.s.s.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.s.w.c.r.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at o.s.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	... 34 frames truncated
```

**Comment by sobychacko** [comment] 2024-11-27 21:39
@Casper-dss Could you please create a minimally reproducible application and provide the GitHub link? That way, we can triage this issue faster. Thanks!

**Comment by sobychacko** [comment] 2024-12-02 19:19
I don't see any Spring Kafka related classes in the stack trace. Looks like this is something application-specific. Please provide more details on the issue or create a reproducible sample.

**Comment by Casper-dss** [comment] 2024-12-03 06:44
We are looking into our application performance monitoring to see if we can find any clues. We will get back to you.

**Comment by sobychacko** [comment] 2024-12-13 18:34
Since this is unrelated to Spring for Apache Kafka (based on the stack trace), we are closing the issue. Feel free to re-open if you have more details or context.

**Closed by sobychacko** 2024-12-13 18:34 UTC
Labels: type: bug, status: waiting for reporter
