### ISSUE TITLE
Using @RetryableTopic with SINGLE_TOPIC does not create predictable retry topic names

### ISSUE THREAD

**Issue by noeloshea** [spring-projects/spring-kafka#2912] opened 2023-11-21 07:50 UTC
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

Both 3.0.6 & 3.0.12

**Describe the bug**

When using a `@RetryableTopic` and `@KafkaListener` combined with `sameIntervalTopicReuseStrategy = SINGLE_TOPIC` in my code, I always expect the retry topic to have a consistent name, even when I change the `attempts` attribute in the `@RetryableTopic` annotation. 

What I expect is:

- my-topic
- my-topic-retry _[This is correct IMHO]_
- my-topic-dlt

but when the `attempts` attribute in the `@RetryableTopic` is less than 3, then the retry topic name is no longer consistent.

- my-topic
- my-topic-retry-**1000** _[This is incorrect IMHO]_
- my-topic-dlt

**To Reproduce**

Reproducing is reasonable simple. In the annotation below you can change `attempts` from 3 to 2 and then via an `AdminClient` get all the topics that were created after startup, this should be equal to the first list mentioned above.

```
    @RetryableTopic(
        attempts = "3",
//        attempts = "2",
        backoff = Backoff(delayExpression = "1000"),
        autoCreateTopics = "true",
        sameIntervalTopicReuseStrategy = SINGLE_TOPIC,
        dltStrategy = ALWAYS_RETRY_ON_ERROR,
        autoStartDltHandler = "true",
    )
    @KafkaListener(
        topics = ["my-topic"],
        autoStartup = "true"
    )
```

**Expected behavior**

In the above example, when I use `SINGLE_TOPIC` with `@RetryableTopic` I always expect the retry topic to have a consistent name as shown above.

**Comment by garyrussell** [comment] 2023-11-21 14:42
Duplicate of https://github.com/spring-projects/spring-kafka/issues/2654

This is resolved in 3.1.0 https://github.com/spring-projects/spring-kafka/pull/2876

**Closed by garyrussell** 2023-11-21 14:42 UTC
Labels: type: bug, status: waiting-for-triage
