### ISSUE TITLE
High CPU-load when broker is down

### ISSUE THREAD

**Issue by sbernauer** [spring-projects/spring-kafka#399] opened 2017-08-22 14:37 UTC
Spring Boot: 1.5.2.RELEASE
Spring-Kafka: 2.0.0.M3
JDK: 1.8.0_121
Kafka: 0.10.2.0

Hi,

i have a single broker instance at localhost and registered a Listener with the Annotation:
`@KafkaListener(topicPartitions = @TopicPartition(topic = "lottoTopic", partitionOffsets = @PartitionOffset(partition = "0", initialOffset = "-1", relativeToCurrent = "true")))
`

This works all fine as expected.
But if I shut the broker down it causes a 100% CPU-load of my SpringBootApplication.
If i start the broker again the cpu-load gets normal again.
This only occurs if i add the topicPartitions-Attribute to the KafkaListener-Annotation.
Without it doesn't happen.

It would be very helpful if you could point out my mistake.

Thanks a lot!

This are my classes:

```
@Configuration
@EnableKafka
public class KafkaConfiguration {
    @Bean
    public Map<String, Object> consumerConfigs() {
        Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "groupId");
        props.put(ConsumerConfig.CLIENT_ID_CONFIG, "groupId");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, true);
        props.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, 1000);
        props.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, 10000);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        return props;
    }

    @Bean
    public ConsumerFactory<String, String> createConsumerFactory() {
        return new DefaultKafkaConsumerFactory<>(consumerConfigs());
    }

    @Bean
    public ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(createConsumerFactory());
        return factory;
    }

@Component
public class Test {
    private static final Logger LOGGER = LoggerFactory.getLogger(Test.class);

    @KafkaListener(topicPartitions = @TopicPartition(topic = "lottoTopic", partitionOffsets = @PartitionOffset(partition = "0", initialOffset = "-1", relativeToCurrent = "true")))
    public void receive(String payload) {
        LOGGER.info("received payload='{}'", payload);
    }
}
```

**Comment by garyrussell** [comment] 2017-08-22 15:39
Thanks for reporting this; unfortunately, it turns out this is a problem with the Kafka client code and out of our control - no error is reported to the listener container.
I reproduced it with pure client code...

	Map<String, Object> configs = new HashMap<>();
	configs.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
	configs.put(ConsumerConfig.GROUP_ID_CONFIG, "gh399");
	configs.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
	configs.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
	KafkaConsumer<String, String> consumer = new KafkaConsumer<>(configs);
	consumer.assign(Collections.singletonList(new org.apache.kafka.common.TopicPartition("foo", 0)));
	while (true) {
		ConsumerRecords<String, String> records = consumer.poll(1000);
		System.out.println(records.count());
	}

I suggest you open an issue agains kafka [on their JIRA](https://issues.apache.org/jira/projects/KAFKA). Please add a link here when you do.

**Comment by sbernauer** [comment] 2017-08-22 19:04
Thanks for your fast and helpful response!
I've created a [Ticket](https://issues.apache.org/jira/browse/KAFKA-5766) at the JIRA of Kafka:
Feel free to amend my ticket

**Comment by garyrussell** [comment] 2017-08-22 21:11
Thanks; closing this; people who are interested can follow the JIRA ticket.

**Closed by garyrussell** 2017-08-22 21:11 UTC
Labels: waiting for reporter
