### ISSUE TITLE
BatchListener commits for every record in the batch instead of last one.

### ISSUE THREAD

**Issue by ltalhouarne** [spring-projects/spring-kafka#262] opened 2017-03-30 20:43 UTC
When using the `BatchListenerAcknowledgment` and acknowledging the `Acknowledgement` given along with the batch with `MANUAL_IMMEDIATE` - it seems that the offset is committed for EACH record in the batch which is very chatty and hinders performance.

The below code in question seems to be the cause: 

```
@Override
public void acknowledge() {
	try {
		Assert.state(ListenerConsumer.this.isAnyManualAck,
		"A manual ackmode is required for an acknowledging listener");
		for (ConsumerRecord<K, V> record : this.records) {
			ListenerConsumer.this.acks.put(record);
		}
	} catch (InterruptedException e) {
		Thread.currentThread().interrupt();
		throw new KafkaException("Interrupted while queuing ack for " + this.records, e);
	}
	if (this.immediate) {
		ListenerConsumer.this.consumer.wakeup();
	}
}
```

I suggest we switch to adding the last record from the list for acknowledgment:

```
@Override
public void acknowledge() {
	try {
		Assert.state(ListenerConsumer.this.isAnyManualAck,
		"A manual ackmode is required for an acknowledging listener");
		if(!this.records.isEmtpy()) {
                     	ListenerConsumer.this.acks.put(this.records.get(this.records.length() - 1));
                }
	} catch (InterruptedException e) {
		Thread.currentThread().interrupt();
		throw new KafkaException("Interrupted while queuing ack for " + this.records, e);
	}
	if (this.immediate) {
		ListenerConsumer.this.consumer.wakeup();
	}
}
```

**Comment by garyrussell** [comment] 2017-03-30 20:52
That's by design; the manual methods are entirely in your domain - you have complete control of when the offset is committed. You should only acknowledge when you want the commit applied. If you want to commit at the end of each batch, let the container do the commits (`AckMode.BATCH`).

**Comment by garyrussell** [comment] 2017-03-30 20:53
Oops; sorry; misread the issue.

**Comment by artembilan** [comment] 2017-03-30 20:54
Oh! That is good catch!

Meanwhile I am fully agree with you that no reason to commit offsets for all the records in batch, I think we can't make an assumption that the last one has the highest offset.
So, my suggestion is to iterate throughout the `this.records` to find max `offset`.
I won't mind if there is really some provement that "the max is always in the end of batch" .

Contribution are welcome!

**Comment by ltalhouarne** [comment] 2017-03-30 20:56
Agreed. The highest offset needs to be committed, not necessarily the last item on the list. 
I would be happy to work on it and submit a PR.

**Comment by ltalhouarne** [comment] 2017-03-31 02:09
@artembilan It was actually a bit more than the highest offset in the list. As your tests demonstrated, not all messages might be from the same partition. Therefore, there was a need for getting the highest offset per partition.

**Comment by ltalhouarne** [comment] 2017-03-31 02:29
@artembilan It was actually a bit more than finding the highest offset from the list. As your tests demonstrated, the batch might contain records from different partitions. Therefore, there was a need to find the highest offset for each partition.

**Comment by artembilan** [comment] 2017-03-31 15:20
Fixed via https://github.com/spring-projects/spring-kafka/commit/db0516d786d044cd83237719b8e715be30c05f91

**Closed by artembilan** 2017-03-31 15:20 UTC
Labels: bug, in pr
