### ISSUE TITLE
FailedRecordTracker cannot handle multiple failed records from different partitions -> can cause infinite loop

### ISSUE THREAD

**Issue by paoying** [spring-projects/spring-kafka#1237] opened 2019-09-16 07:07 UTC
Here is my configuration:
Kafka topic has **6 partitions** while there is **only 1** consumer.
`
```java
    @Bean
    public ConcurrentKafkaListenerContainerFactory kafkaListenerContainerFactory(
            ConcurrentKafkaListenerContainerFactoryConfigurer configurer,
            ConsumerFactory<Object, Object> kafkaConsumerFactory,
            KafkaTemplate<Object, Object> tempalte) {
        ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
        configurer.configure(factory, kafkaConsumerFactory);
        factory.setErrorHandler(new SeekToCurrentErrorHandler(new DeadLetterPublishingRecoverer(tempalte), 3));
        return factory;
    }
````

Here is how to reproduce the issue: if there are multiple failed records processed by the same FailedRecordTracker, it will always think it's a new failure and will never fall back to recoverer.

Sample code to reproduce the issue:

**Producer:**
`
```java
@Component
@Slf4j
public class KafkaProducer {
    @Autowired
    private KafkaTemplate<Object, Object> kafkaTemplate;


    @Scheduled(fixedDelayString = "5000")
    public void produceRandomMessages() {
        Random rand = new Random();
        String key = Integer.toString(rand.nextInt());
        String value = Integer.toString(rand.nextInt());
        kafkaTemplate.send("kafka.demo.message", key, value);
        log.info("Sent message {}: {}", key, value);
    }
}
````

**Consumer:**
`
```java
@Component
@Slf4j
public class KafkaConsumer {

    @KafkaListener(topics = "kafka.demo.message")
    public void consume(ConsumerRecord<String, String> record) {
        log.info("Got message {}:{}", record.key(), record.value());
        if (Integer.parseInt(record.key()) % 10 == 0) {
            log.info("fake failure scenario, consume failed for message {}:{}", record.key(), record.value());
            //it's easy to make every partition's live offset to be set to an failed record 
            throw new RuntimeException();
        }
    }

    @KafkaListener(topics = "kafka.demo.message.DLT")
    public void consumeFailed(ConsumerRecord<String, String> record) {
        log.info("Got failed message {}:{}", record.key(), record.value());
    }
}
````

**A brief cause analysis:**

When you start this, the consumer will always be processing failed records, since FailedRecordTracker compare the new failed rcord with the previous failed record, and it turns out the new record is different so the recoverer process will never start if you get FailedRecordTracker stuck with multiple different failed records from different partitions.

**Affects Version(s):** 2.2.8

**Comment by garyrussell** [comment] 2019-09-16 13:08
It is true that we assume the records will always arrive in the same order.

Are you saying the next poll might get the records in a different order?

**Comment by artembilan** [comment] 2019-09-16 13:31
Sounds like this one is related as well: https://github.com/spring-projects/spring-kafka/issues/1234

**Comment by garyrussell** [comment] 2019-09-16 19:24
Using the sample provided in https://github.com/spring-projects/spring-kafka/issues/1234, I can see that we don't always get the records in the same order after the seek operation.

**Comment by artembilan** [comment] 2019-09-16 19:27
> in the same order after the seek operation.

Shouldn't we need to report that against Apache Kafka then?

I don't mind to fix such a logic on our side, though.

Thanks for confirming that, Gary!

I wonder what is wrong with my sample then, so I can't reproduce it 😢

**Comment by garyrussell** [comment] 2019-09-16 19:45
I don't think it's necessarily a bug with Kafka - let's say new records arrive for another partition during the current poll. After the seeks are performed, it is certainly possible that these new records will appear before the records from the  sought partitions.

**Comment by artembilan** [comment] 2019-09-16 21:58
This issue is duplicate of https://github.com/spring-projects/spring-kafka/issues/1234.
And that one has been fixed.

**Comment by paoying** [comment] 2019-09-17 15:02
> This issue is duplicate of #1234.
> And that one has been fixed.

cool, seems f277c06b03b7b3e06ca4e2050cfd0846133a7987 can fix this

**Comment by paoying** [comment] 2019-09-17 15:08
> It is true that we assume the records will always arrive in the same order.
> 
> Are you saying the next poll after the seek might get the records in a different order?

I think the issue is there even records from different partitions come in the same order.

Eg. suppose a consumer got assigned partitions 1-3, record 1 from partition 1 failed, then record 2 from partition 2 failed, then record 3 from partition 3 failed. And then this pattern goes on, but FailedRecordTracker compare record 2 with record 1, it's always different and always return false for the FailedRecordTracker.skip()

**Comment by garyrussell** [comment] 2019-09-17 15:11
Right; so now we keep state for each topic/partition instead of a single state.

**Closed** 2019-09-18 00:56 UTC
Labels: duplicate
