### ISSUE TITLE
Spring Boot 2.0.0.M3 project using Kafka requires spring-retry

### ISSUE THREAD

**Issue by grahamtriggs** [spring-projects/spring-kafka#384] opened 2017-08-08 15:50 UTC
Had to add explicit spring-retry dependency to a generated Spring boot Maven pom.xml that uses Kafka, otherwise fails with class not found during tests.

**Comment by artembilan** [comment] 2017-08-08 15:56
Well, we definitely need `spring-retry` when we would like to use `@EnableKafka` which is based on the `AbstractKafkaListenerContainerFactory`. And that one really requires `RetryTemplate`.
But (!). That doesn't mean that you can't use Spring Kafka without `@EnableKafka`. Therefore you don't need `spring-retry`.

Maybe your idea to make some change in the Spring Boot do not register `@EnableKafka` infrastructure if there is no `spring-retry` ?

What is your request here BTW, please?

**Comment by garyrussell** [comment] 2017-08-08 16:01
@artembilan - what was the purpose of this change... 

https://github.com/spring-projects/spring-kafka/commit/814915c885973667714a11b6a9c5ad37c53fa695#diff-c197962302397baf3a4cc36463dce5eaR146

... which I believe is the root cause?

**Comment by artembilan** [comment] 2017-08-08 16:06
Oh! I did that. 

OK. If you think that `spring-retry` must be there forever, let's reinstate!

Really don't remember why I decided to `optional` it. Sorry...

**Comment by artembilan** [comment] 2017-08-08 17:20
Fixed via https://github.com/spring-projects/spring-kafka/commit/532a3072d90718f08228753dda8131c53fb60664.

Thank you for the catch, @grahamtriggs !
And @garyrussell for the pointer.

That's how it is much better to have a review in project and work through the PRs 😄

**Closed by artembilan** 2017-08-08 17:20 UTC
