### ISSUE TITLE
Scala Math Loading Error

### ISSUE THREAD

**Issue by bobbymlp** [spring-projects/spring-kafka#1608] opened 2020-11-04 00:41 UTC
**Affects Version(s):** 2.5.7.RELEASE , possibly earlier versions too

I get the error below trying to run kafka tests with the kafka broker enabled in the latest release

> java.lang.IllegalStateException: Failed to load ApplicationContext
> 
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
> 	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
> 	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
> 	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
> 	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:406)
> 	at org.springframework.kafka.test.context.EmbeddedKafkaContextCustomizer.customizeContext(EmbeddedKafkaContextCustomizer.java:116)
> 	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:302)
> 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
> 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
> 	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
> 	... 25 more
> Caused by: java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
> 	at kafka.api.ApiVersion$.orderingByVersion(ApiVersion.scala:45)
> 	at kafka.api.ApiVersion.compare(ApiVersion.scala:139)
> 	at kafka.api.ApiVersion.compare$(ApiVersion.scala:138)
> 	at kafka.api.KAFKA_2_5_IV0$.compare(ApiVersion.scala:339)
> 	at kafka.api.KAFKA_2_5_IV0$.compare(ApiVersion.scala:339)
> 	at scala.math.Ordered.$greater$eq(Ordered.scala:91)
> 	at scala.math.Ordered.$greater$eq$(Ordered.scala:91)
> 	at kafka.api.KAFKA_2_5_IV0$.$greater$eq(ApiVersion.scala:339)
> 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1561)
> 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1269)
> 	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:313)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
> 	... 34 more
> Caused by: java.lang.ClassNotFoundException: scala.math.Ordering$$anon$7
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 47 more

Is there an issue with the scala versions being loaded on the test version? I'm making the following imports

```
    implementation 'org.apache.kafka:kafka_2.12:2.5.1'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test:2.5.7.RELEASE'`
```

**Comment by garyrussell** [comment] 2020-11-04 15:05
This is a problem with Jackson pulling in an incompatible scala library; Spring Boot changed the jackson version to 2.11.3.

See [here](https://github.com/spring-projects/spring-kafka/issues/1604#issuecomment-719569056) - you need to explicitly specify a couple of scala jars.

This is a duplicate of https://github.com/spring-projects/spring-kafka/issues/1604

**Closed by garyrussell** 2020-11-04 15:05 UTC
Labels: duplicate

**Comment by bobbymlp** [comment] 2020-11-04 22:56
Thank you for the help Gary, Hopefully this can be resolved in the next spring boot version.

**Comment by garyrussell** [comment] 2020-11-04 23:07
I don't believe it will. See the boot issue referenced in #1604 for more discussion.

**Comment by garyrussell** [comment] 2020-11-04 23:13
https://github.com/spring-projects/spring-boot/issues/23979

You could also upgrade to boot 2.4 which uses Spring Kafka 2.6 and doesn't suffer from this problem.
