### ISSUE TITLE
EmbeddedKafka: Admin client cannot connect to broker Kafka 3.4.1 spring boot 3.1.1

### ISSUE THREAD

**Issue by mohan404** [spring-projects/spring-kafka#2766] opened 2023-08-04 18:28 UTC
Spring boot: 3.1.1
Kafka: 3.4.1
OS: Windows

Admin client timing out and broker not available:
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2023-08-04T19:14:10.737+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.

**Sample code**
```java
@EmbeddedKafka(partitions = 1)
@SpringBootTest
class SpringkafkaApplicationTests {
	

	@Autowired
    private EmbeddedKafkaBroker embeddedKafka;


	@Test
	void method1ProducerAndConsumer() {

		ArrayList<String> topics = new ArrayList<>();
		topics.add("topic1");
		topics.add("topic2");

		
		Map<String,Object> config = KafkaTestUtils.consumerProps("group1", "true", embeddedKafka);
		config.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
		
		KafkaConsumer<Integer, String> consumer1 = new KafkaConsumer<>(config);
		consumer1.subscribe(topics.subList(0, 1));
		
		
		KafkaConsumer<Integer, String> consumer2 = new KafkaConsumer<>(
				KafkaTestUtils.consumerProps("group2", "true", embeddedKafka));
		consumer2.subscribe(topics);
		//consumer2.seekToEnd(null);
		
		KafkaProducer<Integer, String> producer = new KafkaProducer<>(KafkaTestUtils.producerProps(embeddedKafka));
		producer.send(new ProducerRecord<Integer, String>("topic1", 1, "message11"));
		producer.send(new ProducerRecord<Integer, String>("topic2", 2, "message21"));
		producer.flush();
		producer.close();




		ConsumerRecords<Integer, String> recs = KafkaTestUtils.getRecords(consumer1);
		consumer1.commitAsync();
		
		Assertions.assertEquals(1, recs.count());
		
		recs = KafkaTestUtils.getRecords(consumer2);
		consumer2.commitAsync();

		Assertions.assertEquals(2, recs.count());	

	}
```

**### Logs:**
2023-08-04T19:14:10.133+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 3.4.1
2023-08-04T19:14:10.133+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 8a516edc2755df89
2023-08-04T19:14:10.133+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1691172850133
2023-08-04T19:14:10.138+01:00  INFO 28940 --- [| adminclient-1] o.a.kafka.common.utils.AppInfoParser     : App info kafka.admin.client for adminclient-1 unregistered
2023-08-04T19:14:10.138+01:00  INFO 28940 --- [| adminclient-1] o.a.k.c.a.i.AdminMetadataManager         : [AdminClient clientId=adminclient-1] Metadata update failed

org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata

2023-08-04T19:14:10.143+01:00  INFO 28940 --- [| adminclient-1] o.a.k.clients.admin.KafkaAdminClient     : [AdminClient clientId=adminclient-1] Timed out 1 remaining operation(s) during close.
2023-08-04T19:14:10.148+01:00  INFO 28940 --- [| adminclient-1] o.apache.kafka.common.metrics.Metrics    : Metrics scheduler closed
2023-08-04T19:14:10.148+01:00  INFO 28940 --- [| adminclient-1] o.apache.kafka.common.metrics.Metrics    : Closing reporter org.apache.kafka.common.metrics.JmxReporter
2023-08-04T19:14:10.148+01:00  INFO 28940 --- [| adminclient-1] o.apache.kafka.common.metrics.Metrics    : Metrics reporters closed
2023-08-04T19:14:10.168+01:00  INFO 28940 --- [           main] c.m.s.SpringkafkaApplicationTests        : Starting SpringkafkaApplicationTests using Java 17.0.5 with PID 28940 (started by Archu in E:\Study\gitrepo\code\myspringboot\springkafka)
2023-08-04T19:14:10.169+01:00  INFO 28940 --- [           main] c.m.s.SpringkafkaApplicationTests        : No active profile set, falling back to 1 default profile: "default"
2023-08-04T19:14:10.171+01:00  INFO 28940 --- [=alterPartition] k.s.BrokerToControllerRequestThread      : [BrokerToControllerChannelManager broker=0 name=alterPartition]: Recorded new controller, from now on will use node localhost:62154 (id: 0 rack: null)
2023-08-04T19:14:10.219+01:00  INFO 28940 --- [name=forwarding] k.s.BrokerToControllerRequestThread      : [BrokerToControllerChannelManager broker=0 name=forwarding]: Recorded new controller, from now on will use node localhost:62154 (id: 0 rack: null)

023-08-04T19:14:10.734+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 3.4.1
2023-08-04T19:14:10.734+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 8a516edc2755df89
2023-08-04T19:14:10.734+01:00  INFO 28940 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1691172850734
2023-08-04T19:14:10.737+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.
2023-08-04T19:14:10.739+01:00  WARN 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2023-08-04T19:14:10.841+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.
2023-08-04T19:14:10.842+01:00  WARN 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2023-08-04T19:14:10.942+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.
2023-08-04T19:14:10.943+01:00  WARN 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2023-08-04T19:14:11.145+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.
2023-08-04T19:14:11.145+01:00  WARN 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2023-08-04T19:14:11.548+01:00  INFO 28940 --- [| adminclient-2] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-2] Node -1 disconnected.
2

**Comment by garyrussell** [comment] 2023-08-04 19:06
You don't have an `AdminClient` in your tests. If you are testing against a Boot app that has `NewTopic` beans, Boot will try to provision them. You must set the `spring.kafka.bootstrap-servers` property to point to the embedded broker; the easiest way to do that is with

    @EmbeddedKafka(bootstrapServersProperty = "spring.kafka.bootstrap-servers")
    
This will be the default starting with the next spring-kafka release (3.0.10). https://github.com/spring-projects/spring-kafka/issues/2750

**Comment by sobychacko** [comment] 2024-02-14 16:52
Closing this issue based on the answer Gary provided, and it's been a while since there has been any activity on this issue.

**Closed by sobychacko** 2024-02-14 16:52 UTC
Labels: question, status: waiting for reporter

**Comment by norbson** [comment] 2024-05-17 14:15
Hello,

I think that there is a bug.
Spring boot 2.3.2
Spring kafka 3.2.1

Admin client works ONLY if we use default value for  bootstrapServersProperty which is "spring.kafka.bootstrap-servers"
Any custom value cause above error.

Admin client should be initialized with adequate property based on bootstrapServersProperty value, not hardcoded to  "spring.kafka.bootstrap-servers". Other way, bootstrapServersProperty configuration does not make more sens.

**Comment by sobychacko** [comment] 2024-05-17 15:33
@norbson That Spring Boot version (`2.3.2`) is very old and out of support. There is no Spring Kafka `3.2.1`, the current GA is on `3.1.x` and the `3.2.0` GA is imminent.

**Comment by norbson** [comment] 2024-05-17 17:09
Sorry its typo, correct is
Spring boot 3.2.3
Spring kafka 3.1.2

**Comment by sobychacko** [comment] 2024-05-17 22:07
@norbson `spring.kafka.bootstrapServers` is a Spring Boot property, which is the default set for Embedded Kafka's `bootstrapServersProperty`. You can change this default in your test, but that breaks the `KafkaAdmin` bean auto-configured by Spring Boot. If you are overriding the `bootstrapServersProperty` from the default, then I think you need to provide a custom `KafkaAdmin` bean in your test.

**Comment by norbson** [comment] 2024-05-18 18:45
Sure, below line in test config also solve the problem
`spring.kafka.bootstrap-servers: ${custom.bootstrapServersProperty}`

If its by design behaviour it exhaust the topic.

**Comment by jollyamit** [comment] 2024-07-10 21:16
EmbeddedKafka opens a random port and it setup/override the new host/port string in spring config i.e. spring.kafka.bootstrap-servers. So you need to create the Admin client using spring.kafka.bootstrap-servers property or autowire EmbeddedKafkaBroker embeddedKafka bean in your test and use embeddedKafka.getBrokersAsString() to get the exact server/port EmbeddedKafka broker has started in your test.

            Properties properties = new Properties();
            properties.put("bootstrap.servers", embeddedKafka.getBrokersAsString());
            properties.put("client.id","java-admin-client");
            adminClient = AdminClient.create(properties);
