### ISSUE TITLE
org.springframework.kafka.support.Acknowledgment)' threw exception; nested exception is java.lang.NullPointerException; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by xzhan** [spring-projects/spring-kafka#2651] opened 2023-03-31 07:47 UTC
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

2.8.10

**Describe the bug**

While we have consume messages, we do manual ACK for batch poll message, while do message deserilize we got below error.

Records discarded: jp3_meeting_recording_webex_notification-21@14963
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.cisco.webex.notificationservice.component.compliance.listener.ComplianceRecordingMessageListener.listen(java.util.List<org.apache.kafka.clients.consumer.ConsumerRecord<?, ?>>,org.springframework.kafka.support.Acknowledgment)' threw exception; nested exception is java.lang.NullPointerException; nested exception is java.lang.NullPointerException
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2719) ~[spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:2317) ~[spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:2287) ~[spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:2230) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:2140) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:2023) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2002) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1375) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1366) [spring-kafka-2.8.10.jar:2.8.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1257) [spring-kafka-2.8.10.jar:2.8.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
	Suppressed: org.springframework.kafka.listener.ListenerExecutionFailedException: Restored Stack Trace
		at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:363) ~[spring-kafka-2.8.10.jar:2.8.10]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.invoke(BatchMessagingMessageListenerAdapter.java:180) ~[spring-kafka-2.8.10.jar:2.8.10]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:172) ~[spring-kafka-2.8.10.jar:2.8.10]
		at org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:61) ~[spring-kafka-2.8.10.jar:2.8.10]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:2297) ~[spring-kafka-2.8.10.jar:2.8.10]

**Comment by xzhan** [comment] 2023-03-31 08:07
my question is: as long as we catch NPE, and do ACK on final module , it will final ACK back . right @garyrussell

**Comment by artembilan** [comment] 2023-03-31 13:47
The `2.8.x` is out of open source support already.
Please, see if you can upgrade to the latest one: https://spring.io/projects/spring-kafka#support.

Also it is not clear from your stack trace where that NPE comes from.
I also don't know what is `final module` and what is `final ACK`.

Would be great if you can provide a simple project to let us to reproduce and investigate.

**Comment by xzhan** [comment] 2023-04-04 08:09
Hi @artembilan  thx for you pay attention on this , we found the case is our application code have NPE. Detail biz flow as below
1. pull message with batch model , but we pull only one message and we filter it then we do print metrics happen NPE.
2. Finally we do not ACK this case

But on the next time we will continue pull batch message would be more than 1 , it include the message we will filter and finally we do print metrics and do ACK for batch . it will be ACK

**Comment by garyrussell** [comment] 2023-05-08 20:56
Closing due to no user response. If you are still having issues, please reopen and provide the requested information, or start a discussion on the discussions tab.

**Closed** 2023-05-08 20:57 UTC
Labels: status: invalid
