### ISSUE TITLE
A message with missing fields is sent to retries

### ISSUE THREAD

**Issue by IgorPiven** [spring-projects/spring-kafka#3143] opened 2024-03-19 12:36 UTC
Apache Kafka 2.7.14, Spring Boot 2.7.14

I use @RetryableTopic and faced following problem: if incoming message doesn't contain the fields which are in POJO class, such fields get null value. I expect the outcoming message go further to receiving Kafka but it is put to retry-0 topic. Then goes to retry-1 and finally do Dtl-topic.

```
@RetryableTopic(
            topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_INDEX_VALUE,
            backoff = @Backoff(delay=3_600_000 ,
                    multiplier=2,
                    maxDelay=14_400_000),
            attempts = "4",
            kafkaTemplate = "templateKafka")
    @KafkaListener(topics = "${kafka.topic}", containerFactory = "kafkaListenerContainerFactory")

    public void listenTopic(@Payload @Valid TopicDto dto) {

    kafkaTemplate.send(outputTopic, dto);
   }
```
Producer configs:

```
    public ProducerFactory<String, Object> producerFactory() {
        Map<String, Object> props = new HashMap<>();

        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, servers);
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);
        props.put(ErrorHandlingDeserializer.VALUE_DESERIALIZER_CLASS, JsonSerializer.class.getName());

        props.put("sasl.jaas.config",
                "org.apache.kafka.common.security.plain.PlainLoginModule required " + String.format("username=\"%s\" password=\"%s\";", user, password));

        props.put("security.protocol", "SASL_PLAINTEXT");
        props.put("sasl.mechanism", "PLAIN");


        return new DefaultKafkaProducerFactory<>(props);
    }

    @Bean(name = "templateKafka")
    public KafkaTemplate<String, Object> kafkaTemplate() {
        return new KafkaTemplate<>(producerFactory());
    }
}
```

As far as I understand it is correct that missing fields get null value. But why outcomming message goes to retries?

**Comment by artembilan** [comment] 2024-03-19 14:26
First of all those version are out of open source support, so no way we are going to look into that deeper.
Secondly I see you do `@Valid TopicDto dto`. So, if some field is `null`, and it is not supposed to be by validation, then respective exception is thrown. And according to your `@RetryableTopic` configuration, it is not a surprise that this record goes for retries.
Not sure what else you would expect since whatever you show so far is valid use-case for retries.

**Comment by IgorPiven** [comment] 2024-03-19 14:38
@artembilan thanks for reply! As far as I understand if an exception is thrown the message goes to dlt, doesn't it? In retries it goes if a broker isn't available. Or am I wrong with that?

**Comment by artembilan** [comment] 2024-03-19 14:41
No. That' not correct assumption. It is called "retry" for a reason. And exception is indeed a trigger for such a logic.
It goes to DLT only when all the retries attempts are exhausted. 
If broker would not be available, you would not receive a record in your consumer.
More over this `@RetryableTopic` feature is rally done with the fact that we send a failed record into some other topic and so on.
Please, consult more with docs: https://docs.spring.io/spring-kafka/reference/retrytopic.html.

Closing as `Works as Designed`

**Closed by artembilan** 2024-03-19 14:41 UTC
Labels: status: waiting for reporter
