### ISSUE TITLE
EmbeddedKafkaRule does not delete temporary directories

### ISSUE THREAD

**Issue by apanasevich** [spring-projects/spring-kafka#928] opened 2019-01-09 16:07 UTC
Hi, 

I've faced the problem that EmbeddedKafkaRule does not delete temporary directories. Here is a simple example https://github.com/apanasevich/embeded-kafka-rule

Every run of EmbededKafkaTest#example on Windows leaves non-empty directory with zookeeper log file in user's temporary directory.

**Comment by artembilan** [comment] 2019-01-09 16:50
We do in the `after()` implementation of the rule something like this:
```
CoreUtils.delete(kafkaServer.config().logDirs());
...
this.zookeeper.shutdown();
```

So, if you say that dirs are still there in the tmp user dir, then it is not what we can control from Spring level.

I would recommend to consult with Apache Kafka on the matter if you find this as a problem.

I use Windows as well and the latest Kafka client works pretty stable for me here. I might just not noticed those dirs in my tmp though, but according the code it doesn't look like we can do anything else to clean up them properly.

**Comment by garyrussell** [comment] 2019-01-09 16:55
I just looked at NiFi's implementation

```java
        if (this.started) {
            logger.info("Shutting down Kafka server");
            this.kafkaServer.shutdown();
            this.kafkaServer.awaitShutdown();
            logger.info("Shutting down Zookeeper server");
            this.shutdownZookeeper();
            logger.info("Embedded Kafka is shut down.");
            this.cleanupKafkaWorkDir();
            this.started = false;
        }
```

https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-0-8-processors/src/test/java/org/apache/nifi/processors/kafka/test/EmbeddedKafka.java

**Comment by apanasevich** [comment] 2019-01-17 07:13
I've created [an issue](https://issues.apache.org/jira/browse/ZOOKEEPER-3248) in Apache tracker.

**Comment by FNaughton** [comment] 2019-01-22 11:58
Looks like might be related to / has same root cause as - https://issues.apache.org/jira/browse/KAFKA-6647

**Comment by artembilan** [comment] 2019-04-11 17:29
Closed as *Won't Fix*.
See mentioned above Apache Kafka JIRAs.
Should be addressed automatically after upgrade into a Kafka Client version with the fix.

**Closed by artembilan** 2019-04-11 17:29 UTC
Labels: waiting for reporter
