### ISSUE TITLE
strange exception

### ISSUE THREAD

**Issue by z0mb1ek** [spring-projects/spring-kafka#1289] opened 2019-11-01 14:13 UTC
Hi. We use latest kafka and spring kafka 2.3.0
I see such error:
```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.getSkipPredicate(SeekToCurrentErrorHandler.java:292)
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:257)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1079)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:896)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
and it push it for every 3ms. Can we handle it more correctly?

**Comment by garyrussell** [comment] 2019-11-01 14:30
It's a bug.

However, we should only ever call this error handler with some records, unless some general exception occurred on the consumer thread outside of processing records (e.g. commit error).

I would be interested to know the root cause (the exception that caused the error handler to be called). Is there any more information in the logs?

But, we should check for an empty list.

This will be fixed in 2.3.2, which is scheduled to be released on Monday.

**Closed** 2019-11-01 15:15 UTC
Labels: type: bug

**Comment by z0mb1ek** [comment] 2019-11-04 21:14
@garyrussell big thx for your work!!! But now I see exception without my timeout(30s on error) with:
```
java.lang.IllegalStateException: This error handler cannot process 'SerializationException's directly; please consider configuring an 'ErrorHandlingDeserializer2' in the value and/or key deserializer
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:187)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1110)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:902)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition notifications_messages-1 at offset 18. If needed, please seek past the record to continue consumption.
Caused by: org.springframework.messaging.converter.MessageConversionException: failed to resolve class name. Class not found [lc.forward.liza.extservice.mb.notifications.models.MessageItem]; nested exception is java.lang.ClassNotFoundException: lc.forward.liza.extservice.mb.notifications.models.MessageItem
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:138)
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:99)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:425)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1264)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3600(Fetcher.java:124)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1488)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1600(Fetcher.java:1328)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:641)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:602)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1263)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1225)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:982)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:938)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:890)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: lc.forward.liza.extservice.mb.notifications.models.MessageItem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:277)
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:134)
	... 17 more
```

every 10ms(

**Comment by garyrussell** [comment] 2019-11-04 21:22
Right - read the message

>java.lang.IllegalStateException: This error handler cannot process 'SerializationException's directly; please consider configuring an 'ErrorHandlingDeserializer2' in the value and/or key deserializer

>Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition notifications_messages-1 at offset 18. If needed, please seek past the record to continue consumption.

>Caused by: java.lang.ClassNotFoundException: lc.forward.liza.extservice.mb.notifications.models.MessageItem

You need to protect against deserialization exceptions by using an `ErrorHandlingDeserializer2` as [discussed in the documentation](https://docs.spring.io/spring-kafka/docs/2.3.2.RELEASE/reference/html/#error-handling-deserializer).

**Comment by z0mb1ek** [comment] 2019-11-04 21:30
@garyrussell yes, I see. You asked about root cause, that is why I post a stask =) Big thx!
