### ISSUE TITLE
Kafka creates a lot of major GC

### ISSUE THREAD

**Issue by aghosh1234** [spring-projects/spring-kafka#210] opened 2016-12-03 17:38 UTC
When kafka has a huge lags lets say 40K , kafka consumer codes started a lot of major GC, even we restart the application or kafka servers but not any improvements.It slows down the consumer message processing. It looks like a huge number of kafka-listener thread gets created. How we can control the major GC? Is there any way to nullify the thread instances?

**Comment by artembilan** [comment] 2016-12-03 17:53
Would you mind to clarify what is the problem from Spring Kafka perspective?

Looking to your description, it sounds like a problem on the Kafka side directly.

Thanks

**Comment by aghosh1234** [comment] 2016-12-03 17:57
Spring kafka creates a lot of kafka-listener thread and make the major GC when there is huge offset lag.

**Comment by aghosh1234** [comment] 2016-12-03 17:58
private void startInvoker() {
			
				ListenerConsumer.this.invoker = new ListenerInvoker();
			
			ListenerConsumer.this.listenerInvokerFuture = this.containerProperties.getListenerTaskExecutor()
					.submit(ListenerConsumer.this.invoker);
		}


is it creating a lot of thread?

**Comment by artembilan** [comment] 2016-12-03 18:05
No, just one.

We submit a task to be executed as long-live loop in the one thread. It monitors an internal queue for messages to process.

Would you mind to share some configuration and test-case to play from our side?

**Comment by aghosh1234** [comment] 2016-12-03 18:13
Sure. How long the thread will be lived? Can we control the creation of this thread? Why we are creating new thread instead of using one thread pool?

Use case: Lets push 50 K messages by the producer to a topic and start the consumer and we see a lot of major GCs. In our case we kept 2 listeners for 2 topics and concurrency=3. 

Here is our consumer settings:

group.id=ps-consumer-group
enable.auto.commit=false
request.timeout.ms=120001
session.timeout.ms=120000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=com.comcast.provisioning.provisioning_.kafka.CustomMessageDeSer
client.id=ps
auto.offset.reset=earliest
kafka.consumer.concurreny=3
max.partitions_fetch_bytes=20485760

And number of partitions of each topic is 105 andapplication is  having 35 instances running on cloud. So total 35*3=105 consumers and 105 partitions , so each consumer maps with one partion.

**Comment by aghosh1234** [comment] 2016-12-03 18:14
And we are manually comitting the offset with Synch mode, we tried Ansynch mode but still same issue.

**Comment by artembilan** [comment] 2016-12-03 18:21
OK. Good. Will try something on the matter the next week.

One more question. 
What is "major GC"? And what kind of object is that about?

If you want control over that `executor`, you can use `ContainerProperties.setListenerTaskExecutor()`.
Although I'm not sure that the problem is with thread instances...
We have only one of them per container instance and it lives until stop. That's why we don't need thread pool there.

**Comment by aghosh1234** [comment] 2016-12-03 18:32
Major Garbage colletion happens 2-3 each minutes for each instance and its not good for any application.

@Override
				public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
					ListenerConsumer.this.assignedPartitions = partitions;
					if (!ListenerConsumer.this.autoCommit) {
						// Commit initial positions - this is generally redundant but
						// it protects us from the case when another consumer starts
						// and rebalance would cause it to reset at the end
						// see https://github.com/spring-projects/spring-kafka/issues/110
						Map<TopicPartition, OffsetAndMetadata> offsets = new HashMap<>();
						for (TopicPartition partition : partitions) {
							offsets.put(partition, new OffsetAndMetadata(consumer.position(partition)));
						}
						if (ListenerConsumer.this.logger.isDebugEnabled()) {
							ListenerConsumer.this.logger.debug("Committing: " + offsets);
						}
						if (CustomKafkaMessageListenerContainer.this.getContainerProperties().isSyncCommits()) {
							ListenerConsumer.this.consumer.commitSync(offsets);
						}
						else {
							ListenerConsumer.this.consumer.commitAsync(offsets,
									CustomKafkaMessageListenerContainer.this.getContainerProperties().getCommitCallback());
						}
					}
					if (ListenerConsumer.this.theListener instanceof ConsumerSeekAware) {
						seekPartitions(partitions, false);
					}
					// We will not start the invoker thread if we are in autocommit mode,
					// as we will execute synchronously then
					// We will not start the invoker thread if the container is stopped
					// We will not start the invoker thread if there are no partitions to
					// listen to
					if (!ListenerConsumer.this.autoCommit && CustomKafkaMessageListenerContainer.this.isRunning()
							&& !CollectionUtils.isEmpty(partitions)) {
					    ListenerConsumer.this.logger.debug("StartInvoked call from the partitions invoked by :: "+ Thread.currentThread().getName());
						startInvoker();
					}
					getContainerProperties().getConsumerRebalanceListener().onPartitionsAssigned(partitions);
				}

this onParttionsAssigned method also calls the startInvoker method? does it create more thread in memory?

**Comment by artembilan** [comment] 2016-12-05 15:46
Hm... Yes, it is. But only when rebalance happens. Typically it is done only once at startup and when something has crashed in Kafka ensemble. 
Anyway in that case the `onPartitionsRevoked()` is called and we perform `stopInvokerAndCommitManualAcks()` to properly finish the task and close its thread.

Right a new thread is created in the `onPartitionsAssigned()` via `startInvoker()`, but that sounds strange if you see rebalance all the time.

Maybe you can consider to play with `pause` options?
```
	/**
	 * When using Kafka group management and {@link #setPauseEnabled(boolean)} is
	 * true, the delay after which the consumer should be paused. Default 10000.
	 */
	private long pauseAfter = DEFAULT_PAUSE_AFTER;

	/**
	 * When true, avoids rebalancing when this consumer is slow or throws a
	 * qualifying exception - pauses the consumer. Default: true.
	 * @see #pauseAfter
	 */
	private boolean pauseEnabled = true;

```

**Comment by aghosh1234** [comment] 2016-12-05 16:04
Can we use a counter and control the creation of invoker thread? Something like:

private void startInvoker() {
			this.logger.debug("Entering the startInvoker method and count is :: "+ListenerConsumer.this.invokerInstanceCount +" and called by :: "+Thread.currentThread().getName());
			if(ListenerConsumer.this.invokerInstanceCount<100){
				ListenerConsumer.this.invokerInstanceCount++;
				ListenerConsumer.this.invoker = new ListenerInvoker();
			}
			ListenerConsumer.this.listenerInvokerFuture = this.containerProperties.getListenerTaskExecutor()
					.submit(ListenerConsumer.this.invoker);
		}

and inside finally block of stopInvokerAndCommitManualAcks() method we can make count down the counter like:

finally {
				ListenerConsumer.this.invokerInstanceCount--;
				this.listenerInvokerFuture = null;
			}

How do you thing is it feasible?

**Comment by artembilan** [comment] 2016-12-05 16:10
Why do we need that? 
How does it help to prevent that GC on threads?

Have you tried your solution with external managed `ThreadPoolExecutor`?
See my comment above: https://github.com/spring-projects/spring-kafka/issues/210#issuecomment-264656003

As I said: the `KafkaMessageListenerContainer` needs and manages only one `ListenerInvoker` instance and, therefore, only one thread for it. 

If you have a problem which causes always rebalance that isn't surprise that we a create new `ListenerInvoker` for each `onPartitionsAssigned()` and destroy it in each `onPartitionsRevoked()`, which finishes for you with GC work, of course.

**Comment by aghosh1234** [comment] 2016-12-05 16:34
Ok thank you. If it does not create many threads , do you know any other code of  KafkaMessageListenerContainer makes the major GC. It happens only when we have lags lets say 40-50 K lag and each message take time to process 2-3 sec. Have you got chance to run the test with our configuration?

**Comment by artembilan** [comment] 2016-12-05 16:38
Well, that isn't surprise that we have `ConsumerRecord`, `Message<?>`, `MessageHeaders`, `ConsumerAcknowledgment` etc instances for all those 40-50 K records in the Kafka topic.

So, maybe that confuses you...

No, I haven't had a chance yet to run you use-case.

**Comment by aghosh1234** [comment] 2016-12-05 16:49
I saw rebalance happens in my case every 2-3 mins and a lot of startInvoker calles. Here is my log snippet for 2 listener classes for two topics:

Searching for: StartInvoked call from the partitions invoked by ::
provisioningService.log(9062): 10:44:18.834 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(9063): 10:44:18.834 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(10233): 10:46:42.990 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(10235): 10:46:42.991 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(12331): 10:50:52.029 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(12337): 10:50:52.030 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(13693): 10:53:34.292 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(13700): 10:53:34.295 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(14984): 10:56:04.260 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(14986): 10:56:04.261 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(17093): 11:00:07.768 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(17097): 11:00:07.770 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(18380): 11:02:49.593 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(18388): 11:02:49.603 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(19692): 11:05:19.940 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(19696): 11:05:19.941 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(23566): 11:09:23.793 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(23570): 11:09:23.794 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(24949): 11:12:06.116 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(24953): 11:12:06.116 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(26151): 11:14:36.087 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(26152): 11:14:36.088 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(28216): 11:18:39.648 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(28220): 11:18:39.650 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(29904): 11:25:28.614 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(29911): 11:25:28.615 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(31084): 11:27:55.673 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(31088): 11:27:55.674 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(31806): 11:30:25.718 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(31813): 11:30:25.725 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(33332): 11:35:25.869 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(33334): 11:35:25.869 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(34206): 11:37:10.961 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(34213): 11:37:10.962 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(35494): 11:39:53.454 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
provisioningService.log(35501): 11:39:53.456 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(36784): 11:42:23.382 [psListenerReq-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerReq-0-kafka-consumer-1
provisioningService.log(36791): 11:42:23.384 [psListenerask-0-kafka-consumer-1] DEBUG c.c.p.p.k.CustomKafkaMessageListenerContainer$ListenerConsumer - StartInvoked call from the partitions invoked by :: psListenerask-0-kafka-consumer-1
Found 38 occurrence(s) in 1 file(s)


So is there any thing wrong in my configuration settings? How so many rebalance happens? Even we don't have any message in topic.

**Comment by aghosh1234** [comment] 2016-12-05 19:32
He is our GS settings for JVM:
-XX:+UseCompressedOops -XX:+UseParNewGC -XX:NewRatio=1 -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark -XX:+DisableExplicitGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+UseCMSInitiatingOccupancyOnly

**Comment by aghosh1234** [comment] 2016-12-05 19:33
Can you please run the test if you get chance ?

**Comment by artembilan** [comment] 2016-12-12 16:29
@aghosh1234 , 

sorry for delay. We were on team meeting the last week.

Well, it still isn't clear to me what's going on with the pause in your use-case and how managed `ThreadPoolExecutor` helps you.
OTOH I'd be glad to help, but I need to see some proper test-case to play from our side.
Plus let us know, finally, which objects in GC are you complaining about.

Thanks

**Comment by garyrussell** [comment] 2017-04-05 15:08
Closed with no response; please reopen if you feel there's still an issue.

**Closed by garyrussell** 2017-04-05 15:08 UTC
Labels: waiting for reporter
