### ISSUE TITLE
No replacement for KafkaSendCallback was found.

### ISSUE THREAD

**Issue by JinseongHwang** [spring-projects/spring-kafka#3330] opened 2024-06-26 07:38 UTC
**Expected Behavior**

**Current Behavior**

```kotlin
fun kafkaSendCallback(message: Any) =
      object : KafkaSendCallback<String, Any> { // compile error, KafkaSendCallback not found
          override fun onSuccess(result: SendResult<String, Any>?) {
          }
          override fun onFailure(ex: KafkaProducerException) {
          }
      }
```

**Context**

- JDK 21
- Kotlin 1.9.24
- Spring Boot 3.2.7
- Spring Kafka 3.1.6

I found the [release notes v2.5.0](https://github.com/spring-projects/spring-kafka/releases/tag/v2.5.0.RELEASE) and noticed the addition of "KafkaSendCallback". It is evident that "KafkaSendCallback" is intended as a replacement for "ListenerFutureCallback".

I am currently using `spring-kafka:3.1.6`, but in this version, "KafkaSendCallback" no longer exists. After searching through subsequent release notes, I couldn’t find any information on what has replaced "KafkaSendCallback". Could you please provide some guidance?

I look forward to seeing it added to the official documentation or wiki.

Thanks. 😄

**Comment by artembilan** [comment] 2024-06-26 15:46
That is replaced with standard `CompletableFuture`.
The code in that old change for Spring for Apache Kafka `2.5.0`: https://github.com/spring-projects/spring-kafka/commit/1810409825757c50ed4c4c1e3eecb75343e587b9#diff-a787aef75a832981d07fcdb8cb93df9b222beeea45f692e75d5f0612ff47d4d9R366
right now looks like this:
```
CompletableFuture<SendResult<Integer, String>> future = template.send("foo", 1, "bar");
future.whenComplete((result, ex) -> {
```
The respective change was made in `2.9.1`: https://github.com/spring-projects/spring-kafka/commit/8336461545d036f3183e6bd8a0488c3b8d3464f9.
Here are release notes: https://github.com/spring-projects/spring-kafka/releases/tag/v2.9.1

Closed as `Works as Designed`

**Closed by artembilan** 2024-06-26 15:46 UTC
Labels: type: enhancement, status: waiting-for-triage
