### ISSUE TITLE
Provide synchronous approach to partially commit batch

### ISSUE THREAD

**Issue by daniel-shuy** [spring-projects/spring-kafka#1915] opened 2021-08-20 16:17 UTC
**Affects Version(s):** 2.7.3

When using  `BatchAcknowledgingMessageListener` to manually control commits, `Acknowledgment#acknowledge()` (commit entire batch) will be synchronous/asynchronous depending on whether `syncCommits` is set to `true`/`false` (assuming it is called from the consumer thread and `ackMode` is `AckMode.MANUAL_IMMEDIATE`).

But when using `Acknowledgment#nack(int, long)` to partial commit a batch, the commit is always done asynchronously, regardless of whether `syncCommits` is `true`/`false`. This has 2 downsides:
- Unless an arbitrarily long sleep time is set, the next `poll()` might be called before the commits complete, resulting in already successfully processed records being polled again
- If the Kafka commit fails, it will not give the caller a chance to handle it (eg. rollback database transaction)

While neither of these issues are dealbreaking (consumers should be idempotent), it would be nice to have a way to partially commit synchronously.

**Comment by daniel-shuy** [comment] 2021-08-24 10:42
@garyrussell thanks for taking this up!

To avoid breaking backwards compatibility, I'm guessing its probably better to create a new method instead of modifying the behavior of `Acknowledgement#nack(int, long)` to maintain backwards compatibility (since the `sleep` parameter will be redundant if it is synchronous anyways), eg.
```java
public interface Acknowledge {
  // ...

  /**
   * Acknowledge the record at an index in a batch - commit the offset(s) of records before and at the index.
   * @param index the index of the record in the batch to acknowledge.
   **/
  void acknowledge(int index);

  // ...
}
```

**Comment by garyrussell** [comment] 2021-08-24 13:56
I am not sure what you men. The sleep parameter is not redundant; it was added because, for transient errors, retrying immediately doesn't usually make sense.

**Comment by daniel-shuy** [comment] 2021-08-24 13:58
Oh, I meant that it will be redundant if `Acknowledgement#nack(int, long)` was changed to synchronous, therefore it would be better to introduce a new method to partial commit synchronously than to modify the behavior of `Acknowledgement#nack(int, long)`

**Comment by garyrussell** [comment] 2021-08-30 20:27
I just got around to looking at the code.

>But when using Acknowledgment#nack(int, long) to partial commit a batch, the commit is always done asynchronously, regardless of whether syncCommits is true/false. This has 2 downsides:

What makes you think that?

All that method does is set the `nackIndex` and `nackSleep` fields.

When the listener exits we decide which records to commit (add to `acks`) and which to re-seek; here

https://github.com/spring-projects/spring-kafka/blob/7aadccbd75f239b46a7350fe1312b756e9819160/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2046-L2057

then

https://github.com/spring-projects/spring-kafka/blob/7aadccbd75f239b46a7350fe1312b756e9819160/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2068-L2074

`processCommits` calls `commitIfNecessary`, which commits sync or asyn depending on the property.

https://github.com/spring-projects/spring-kafka/blob/7aadccbd75f239b46a7350fe1312b756e9819160/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2811-L2816

In fact, we have a test case that verifies the partial batch is commited sync, by default...

https://github.com/spring-projects/spring-kafka/blob/29e93b530da3a3a606c0d2cfea94d93e8577b963/spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTests.java#L202-L205

I changed it to `MANUAL_IMMEDIATE` and it still works (`MANUAL` and `MANUAL_IMMEDIATE` are effectively the same for batch listeners),

**Comment by garyrussell** [comment] 2021-08-30 20:44
Furthermore; committed offsets have nothing to do with what `poll()` returns - it's `position()` that determines the next records retrieved on the poll; seek changes the `position()`.

**Comment by garyrussell** [comment] 2021-08-30 20:56
>`MANUAL` and `MANUAL_IMMEDIATE` are effectively the same for batch listeners.

They are effectively the same, but `MANUAL` is more efficient. `MANUAL_IMMEDIATE` commits them one-at-atime, whereas `MANUAL` commits them as a batch.

We should consider Coercing `MANUAL_IMMEDIATE` to `MANUAL` for batch listeners.

**Comment by garyrussell** [comment] 2021-08-30 22:14
Oh, I can see your point in your second bullet - by async, you mean it is not really immediate, we call commitSync, but later, so you don’t get a chance to catch any exceptions.

I still don’t get the first bullet though.

**Closed** 2021-08-31 21:17 UTC
Labels: status: waiting for reporter

**Comment by daniel-shuy** [comment] 2021-09-01 05:18
@garyrussell thank you, that is exactly what I needed.

What I meant by the first point, is that the purpose of the `sleep` parameter is to give the consumer thread enough time between committing and polling again so that the committed records don't get polled again, since the `nack()` commit was asynchronous. If the commit is synchronous then the `sleep` parameter becomes redundant, which is why I suggested adding a separate method instead, but this approach is fine as well.

**Comment by garyrussell** [comment] 2021-09-01 13:14
>What I meant by the first point, is that the purpose of the sleep parameter is to give the consumer thread enough time between committing and polling again so that the committed records don't get polled again, since the nack() commit was asynchronous. 

That is not true; the sleep parameter is allow you to pause before retrying - consider a transient problem like a database connectivity problem or a broken socket; you might want to wait a few seconds before trying again; trying immediately will consume a lot of processor and generate lots of logs.

Furthermore the commit was not "asynchronous" it was just done after your listener exited, but on the same thread (synchronously by default) and before the next poll.

IMPORTANT: If you catch an exception on the `acknowledge()` or `nack()` call, it (or another exception) must be thrown to the container so the whole batch will be retried.

**Comment by daniel-shuy** [comment] 2021-09-03 15:44
@garyrussell I see, looks like I misunderstood the purpose of the `sleep` parameter, my bad.

> Furthermore the commit was not "asynchronous" it was just done after your listener exited, but on the same thread (synchronously by default) and before the next poll.

That's odd, after I called `nack()` with a `sleep` argument of `0` or a small enough value, the next poll would return the records that were already committed.

**Comment by garyrussell** [comment] 2021-09-03 15:52
I don't see how that's possible, unless a rebalance occured.

For an active consumer, Kafka maintains 2 pointers - `committed offset` - the offset that will be delivered next if the consumer is closed and restarted (or a rebalance occurs involving that partition) and `position` - the next record from this partition to be retrieved on the next `poll()` (it is one more than the last offset retrieved from this partition on the previous poll).

**Comment by daniel-shuy** [comment] 2021-09-03 16:38
After digging deeper into the code:

When `nack(int, long)` is called, it simply sets the `nackIndex` without committing:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2877-L2885

This `nackIndex` is only used in `invokeBatchOnMessage(ConsumerRecords<K, V> records, List)`:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1927-L1943

which is only called by `doInvokeBatchListener(ConsumerRecords, List)`:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1836-L1842

which is called by `invokeBatchListener(ConsumerRecords)` for non-transactional listeners:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1711-L1728

which is only called by `invokeListener(ConsumerRecords)`:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1702-L1709

which is only called by `invokeIfHaveRecords(ConsumerRecords)`:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1269-L1275

which is finally only called by `pollAndInvoke()`:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1233-L1267
`invokeIfHaveRecords()` is called at the end (`L1266`), after `doPoll()` is called (`L1249`). Therefore the commit only happens after the next `poll()`.

So the issue of `poll` returning already acked records is definitely happening.

But my assumption was wrong, the commit is not being done asynchronously. The next `poll` will always return duplicate records regardless of the `sleep` parameter. Looking at `invokeBatchOnMessage(ConsumerRecords<K, V> records, List)` it seems like it was designed this way intentionally, which is odd instead of just committing directly when `nack(int, long)` is called, maybe there is some underlying reason to it:
https://github.com/spring-projects/spring-kafka/blob/d36759e30501cdb416e3e2850e9908f74fd25b88/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1927-L1943

Anyways, your #1932 PR should resolve this issue since now `nack(int, long)` will either commit immediately (for `MANUAL_IMMEDIATE`) or add the to `offsets` (which will be committed by `processCommits()` at the start of `pollAndInvoke()`, before the next `poll()`).

**Comment by garyrussell** [comment] 2021-09-03 16:53
I still don't see it, sorry - looking at the 2.7.x branch (which doesn't have my commit)...

https://github.com/spring-projects/spring-kafka/blob/b9421a96344b8d5de72f4db67dc769952d80b8eb/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1929-L1963

Specifically:

https://github.com/spring-projects/spring-kafka/blob/b9421a96344b8d5de72f4db67dc769952d80b8eb/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1956-L1962

>The next poll will always return duplicate records regardless of the sleep parameter. 

One more time, a `poll()` will only return the same records under 3 circumstances.

1. The consumer is retarted
2. A rebalance occurred
3. A seek was performed before the poll.

If none of these conditions apply the poll will return the records at the next `position` as I described above.

If you can provide an [MCRE](https://stackoverflow.com/help/minimal-reproducible-example) that exhibits the behavior you claim, I would love to take a look at it.

**Comment by daniel-shuy** [comment] 2021-09-03 17:00
If you look at the call sequence that I listed, `invokeBatchOnMessage()` is only called after the next `poll()` is performed, hence the records before/at the `nack` index will only be committed after the next `poll()`.

> If you can provide an MCRE that exhibits the behavior you claim, I would love to take a look at it.

Sure, I'll provide one when I have more time.

**Comment by garyrussell** [comment] 2021-09-03 17:05
I still don't understand; `ack.nack()` for a batch listener can only be called on the listener thread (it is enforced).

This means that the thread MUST be downstream of `invokeBatchOnMessageWithRecordsOrList` when `nack` is called, so, we perform the commits immediately, on the same thread, as soon as `invokeBatchOnMessageWithRecordsOrList` exits.

**Comment by daniel-shuy** [comment] 2021-09-06 05:01
You're right, my bad, I didn't realize `invokeBatchOnMessage(ConsumerRecords, List)` was calling `processCommits()` after `invokeBatchOnMessageWithRecordsOrList(ConsumerRecords, List)`.

After further debugging I've confirmed that my issue was happening due to rebalancing, found:
```
Failing OffsetCommit request since the consumer is not part of an active group
```
in the logs.

Thanks for the help, and sorry for the inconvenience 😅
