### ISSUE TITLE
Sending message from transactional Kafka listener: Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION

### ISSUE THREAD

**Issue by evgeniy-khist** [spring-projects/spring-kafka#645] opened 2018-04-13 14:44 UTC
I'm trying to send a message from Kafka listener in the same transaction to have message sending and offset committing in the same transaction but receives an exception: Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION, and the transaction is rolled back.

I've added transaction support to my application (Spring Boot 2, Spring Kafka 2.1.4) using the following approach.

**application.properties**
```properties
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.group-id=transaction-sample
spring.kafka.listener.ack-mode=RECORD

spring.kafka.producer.transaction-id-prefix=transaction-sample-${random.uuid}
```

I've set kafkaTransactionManager to kafkaListenerContainerFactory containerProperties:

```java
@SpringBootApplication
public class KafkaTransactionsSampleApplication {

  @Bean
  public ConcurrentKafkaListenerContainerFactory<?, ?> kafkaListenerContainerFactory(
      ConcurrentKafkaListenerContainerFactoryConfigurer configurer,
      ConsumerFactory<Object, Object> kafkaConsumerFactory,
      KafkaTransactionManager<Object, Object> kafkaTransactionManager) {
    ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
    configurer.configure(factory, kafkaConsumerFactory);
    factory.getContainerProperties().setTransactionManager(kafkaTransactionManager);
    return factory;
  }

  public static void main(String[] args) {
    SpringApplication.run(KafkaTransactionsSampleApplication.class, args);
  }
}
```

Test listener should receive a message from input topic (*transaction-sample-topic-in*), log it, and forward it to the output topic (*transaction-sample-topic-out*). I want message sending and offset committing to be performed in the same transaction.

```java
@Component
public class TestKafkaListener {

  private static final Logger LOGGER = LoggerFactory.getLogger(TestKafkaListener.class);

  public static final String INPUT_TEST_TOPIC = "transaction-sample-topic-in";
  public static final String OUTPUT_TEST_TOPIC = "transaction-sample-topic-out";

  @Autowired
  private KafkaTemplate<String, String> kafkaTemplate;

  @KafkaListener(topics = INPUT_TEST_TOPIC)
  public void listen(ConsumerRecord<String, String> record) {
    LOGGER.info("Received Kafka record from {}: {}", INPUT_TEST_TOPIC, record);
    kafkaTemplate.send(OUTPUT_TEST_TOPIC, record.key(), record.value());
    LOGGER.info("Forwarded Kafka record to {}: {}", OUTPUT_TEST_TOPIC, record);
  }
}
```

In the tests, I've defined embedded Kafka with broker properties allowing to have transaction support with 1 broker instance.

```java
@Bean
public KafkaEmbedded kafkaEmbedded() {
  KafkaEmbedded kafkaEmbedded = new KafkaEmbedded(1, false, 1,
      INPUT_TEST_TOPIC, OUTPUT_TEST_TOPIC);
  kafkaEmbedded.setKafkaPorts(9092);
  kafkaEmbedded.brokerProperty(KafkaConfig.TransactionsTopicReplicationFactorProp(), "1");
  kafkaEmbedded.brokerProperty(KafkaConfig.TransactionsTopicMinISRProp(), "1");
  return kafkaEmbedded;
}
```

When I run a simple test that sends a message to the input topic I receive an exception: Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION. The transaction is rolled back and the message is not forwarded to the output topic.

```java
@TestPropertySource("classpath:test.properties")
@RunWith(SpringRunner.class)
@SpringBootTest
public class KafkaListenerTest {

  @Autowired
  private KafkaEmbedded kafkaEmbedded;

  @Autowired
  private KafkaTemplate<String, String> kafkaTemplate;

  @Test
  public void shouldProcessEvent() throws Exception {
    String testKey = "test_key";
    String testData = "test_data";

    kafkaTemplate.send(INPUT_TEST_TOPIC, testKey, testData);

    try (Consumer<String, String> consumer = createConsumer()) {
      kafkaEmbedded.consumeFromAnEmbeddedTopic(consumer, OUTPUT_TEST_TOPIC);
      ConsumerRecords<String, String> records = KafkaTestUtils.getRecords(consumer);
      Iterator<ConsumerRecord<String, String>> iterator = records.iterator();
      ConsumerRecord<String, String> record = iterator.next();

      assertEquals(testKey, record.value());
      assertEquals(testData, record.value());
      assertFalse(iterator.hasNext());
    }
  }

  private Consumer<String, String> createConsumer() {
    Map<String, Object> consumerProps =
        KafkaTestUtils.consumerProps("test-consumer", "true", kafkaEmbedded);
    consumerProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
    DefaultKafkaConsumerFactory<String, String> cf = new DefaultKafkaConsumerFactory<>(
        consumerProps, new StringDeserializer(), new StringDeserializer());
    return cf.createConsumer();
  }
}
```

The exception is

```
2018-04-13 16:22:46.856 ERROR 141936 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Transaction rolled back

org.springframework.transaction.CannotCreateTransactionException: Could not create Kafka transaction; nested exception is org.apache.kafka.common.KafkaException: TransactionalId transaction-sample-209b149f-7f97-42f6-82e7-257e1ac0d1950: Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION
	at org.springframework.kafka.transaction.KafkaTransactionManager.doBegin(KafkaTransactionManager.java:141) ~[spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.innvokeRecordListenerInTx(KafkaMessageListenerContainer.java:949) [spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:929) [spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:801) [spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689) [spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: org.apache.kafka.common.KafkaException: TransactionalId transaction-sample-209b149f-7f97-42f6-82e7-257e1ac0d1950: Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION
	at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:755) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:749) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.TransactionManager.beginTransaction(TransactionManager.java:215) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.beginTransaction(KafkaProducer.java:564) ~[kafka-clients-1.0.0.jar:na]
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.beginTransaction(DefaultKafkaProducerFactory.java:285) ~[spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.kafka.core.ProducerFactoryUtils.getTransactionalResourceHolder(ProducerFactoryUtils.java:60) ~[spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.kafka.transaction.KafkaTransactionManager.doBegin(KafkaTransactionManager.java:126) ~[spring-kafka-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	... 9 common frames omitted
```

I've created a sample application to reproduce the problem: https://github.com/evgeniy-khist/spring-kafka-transactions-sample

**Comment by garyrussell** [comment] 2018-04-13 15:57
Your test `send()` needs to run in its own transaction:

```java
kafkaTemplate.executeInTransaction(kt ->
    kt.send(INPUT_TEST_TOPIC, testKey, testData));
```

I also fixed your asserts:

```java
assertEquals(testKey, record.key());
assertEquals(testData, record.value());
```

(they were both comparing the value).

**Comment by evgeniy-khist** [comment] 2018-04-13 18:34
@garyrussell thank you. I've checked when test `send()` is done in its own transaction, everything works. It was not obvious that send in test should be in transaction if auto-configured `KafkaTemplate` is used. What is a proper way to get non-transactional template?

**Comment by garyrussell** [comment] 2018-04-13 18:57
You would need to define two producer factories and two templates (one with and one without a transaction id prefix).

I just issued a PR https://github.com/spring-projects/spring-kafka/pull/647 to detect the condition and provide a meaningful exception.

**Comment by garyrussell** [comment] 2018-04-18 12:53
Yes, it works for me - I just ran it again...

![screen shot 2018-04-18 at 8 50 58 am](https://user-images.githubusercontent.com/483832/38933019-d217a8ba-42e5-11e8-8c25-548983387077.png)

```java
package com.example.kafka.sample.transaction;

import static com.example.kafka.sample.transaction.listener.TestKafkaListener.INPUT_TEST_TOPIC;
import static com.example.kafka.sample.transaction.listener.TestKafkaListener.OUTPUT_TEST_TOPIC;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import java.util.Iterator;
import java.util.Map;

import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.kafka.core.DefaultKafkaConsumerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.test.rule.KafkaEmbedded;
import org.springframework.kafka.test.utils.KafkaTestUtils;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit4.SpringRunner;

@TestPropertySource("classpath:test.properties")
@RunWith(SpringRunner.class)
@SpringBootTest
public class KafkaListenerTest {

  @Autowired
  private KafkaEmbedded kafkaEmbedded;

  @Autowired
  private KafkaTemplate<String, String> kafkaTemplate;

  @Test
  public void shouldProcessEvent() throws Exception {
    String testKey = "test_key";
    String testData = "test_data";

    kafkaTemplate.executeInTransaction(kt ->
    	kt.send(INPUT_TEST_TOPIC, testKey, testData));

    try (Consumer<String, String> consumer = createConsumer()) {
      kafkaEmbedded.consumeFromAnEmbeddedTopic(consumer, OUTPUT_TEST_TOPIC);
      ConsumerRecords<String, String> records = KafkaTestUtils.getRecords(consumer);
      Iterator<ConsumerRecord<String, String>> iterator = records.iterator();
      ConsumerRecord<String, String> record = iterator.next();

      assertEquals(testKey, record.key());
      assertEquals(testData, record.value());
      assertFalse(iterator.hasNext());
    }
  }

  private Consumer<String, String> createConsumer() {
    Map<String, Object> consumerProps =
        KafkaTestUtils.consumerProps("test-consumer", "true", kafkaEmbedded);
    consumerProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
    DefaultKafkaConsumerFactory<String, String> cf = new DefaultKafkaConsumerFactory<>(
        consumerProps, new StringDeserializer(), new StringDeserializer());
    return cf.createConsumer();
  }
}
```

**Comment by eklierka** [comment] 2018-04-18 13:53
Test fails on Windows but passes on Ubuntu... probably the issue is related to Windows

**Comment by artembilan** [comment] 2018-04-18 13:56
> probably the issue is related to Windows

Probably the issue is related to the Apache Kafka which doesn't support Windows properly.

Yes, I develop on Windows as well and I really see some issues with Kafka very often, especially with transactions.

I think the issue comes out of the scope of this project.

You can try to raise issue against Apache Kafka and cross-link it here.

Thanks for understanding

**Comment by evgeniy-khist** [comment] 2018-04-27 05:51
@eklierka this is a known Kafka issue: https://issues.apache.org/jira/browse/KAFKA-6052. According to the ticket, fix will be included in the Kafka version 1.1.1.

**Comment by garyrussell** [comment] 2018-05-11 19:06
Closing for now; we can reopen if this tuns out to be a spring-kafka issue.

**Closed by garyrussell** 2018-05-11 19:06 UTC
Labels: waiting for reporter

**Comment by vspiliopoulos** [comment] 2018-06-15 17:20
Hello @eklierka and all!

I tried exactly the above in Windows (spring-kafka-2.1.6.RELEASE) as well and the behavior I am seeing is that the TestKafkaListener.listen() receives the record successfully, but OUTPUT_TEST_TOPIC never received the record. Is this the issue you had on Windows?

From my logs:

`2018-06-15 17:11:05.568 DEBUG 13512 --- [           main] o.s.kafka.test.rule.KafkaEmbedded        : partitions assigned: [transaction-sample-topic-out-0]
2018-06-15 17:11:05.568 DEBUG 13512 --- [ntainer#0-0-C-1] o.s.k.t.KafkaTransactionManager          : Initiating transaction commit
2018-06-15 17:11:05.592  INFO 13512 --- [ntainer#0-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [transaction-sample-topic-in-0]
2018-06-15 17:11:05.592 DEBUG 13512 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Received: 0 records
2018-06-15 17:11:05.592 DEBUG 13512 --- [           main] o.s.kafka.test.rule.KafkaEmbedded        : Subscription Initiated
2018-06-15 17:11:05.592 DEBUG 13512 --- [           main] o.s.kafka.test.utils.KafkaTestUtils      : Polling...
2018-06-15 17:11:05.646 DEBUG 13512 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Received: 1 records
2018-06-15 17:11:05.648 DEBUG 13512 --- [ntainer#0-0-C-1] o.s.k.t.KafkaTransactionManager          : Creating new transaction with name [null]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2018-06-15 17:11:05.648 DEBUG 13512 --- [ntainer#0-0-C-1] o.s.k.t.KafkaTransactionManager          : Created Kafka transaction on producer [CloseSafeProducer [delegate=org.apache.kafka.clients.producer.KafkaProducer@1e959a17]]
2018-06-15 17:11:05.653 DEBUG 13512 --- [ntainer#0-0-C-1] .a.RecordMessagingMessageListenerAdapter : Processing [GenericMessage [payload=test_data, headers={kafka_offset=0, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@456a69df, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=test_key, kafka_receivedPartitionId=0, kafka_receivedTopic=transaction-sample-topic-in, kafka_receivedTimestamp=1529082665320}]]
2018-06-15 17:11:05.653  INFO 13512 --- [ntainer#0-0-C-1] c.e.q.t.s.k.listener.TestKafkaListener   : Received Kafka record from transaction-sample-topic-in: ConsumerRecord(topic = transaction-sample-topic-in, partition = 0, offset = 0, CreateTime = 1529082665320, serialized key size = 8, serialized value size = 9, headers = RecordHeaders(headers = [], isReadOnly = false), key = test_key, value = test_data)
2018-06-15 17:11:05.653  INFO 13512 --- [ntainer#0-0-C-1] c.e.q.t.s.k.listener.TestKafkaListener   : Forwarded Kafka record to transaction-sample-topic-out: ConsumerRecord(topic = transaction-sample-topic-in, partition = 0, offset = 0, CreateTime = 1529082665320, serialized key size = 8, serialized value size = 9, headers = RecordHeaders(headers = [], isReadOnly = false), key = test_key, value = test_data)
2018-06-15 17:11:05.653 DEBUG 13512 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Sending offsets to transaction: {transaction-sample-topic-in-0=OffsetAndMetadata{offset=1, metadata=''}}
2018-06-15 17:12:05.593 DEBUG 13512 --- [           main] o.s.kafka.test.utils.KafkaTestUtils      : Received: 0, []`

**Comment by artembilan** [comment] 2018-06-15 17:52
Yes, I'm observing some issue with Kafka transaction on Windows.
Mostly my thought is like there is some race condition around resource in Apache Kafka client per se.
Would be great if you escalate such an issue to Apache Kafka directly.

Thanks

**Comment by vspiliopoulos** [comment] 2018-06-19 08:12
Thanks @artembilan,

It was indeed a windows related issue, as in my mac it works fine!

**Comment by evgeniy-khist** [comment] 2018-06-21 12:12
Hi @vspiliopoulos .
There is a bug in Kafka 1.0.0 https://issues.apache.org/jira/browse/KAFKA-6052
Due to this bug, Kafka transactions are not working on Windows.
So Kafka transactions sample can't be run on Windows.
The fix to the https://issues.apache.org/jira/browse/KAFKA-6052 is expected to be delivered in Kafka 1.1.1.
