### ISSUE TITLE
Reactor : Spring Kafka

### ISSUE THREAD

**Issue by dsaish3** [spring-projects/spring-kafka#592] opened 2018-02-27 22:13 UTC
I am really sorry to raise this as an issue. I am either requesting or checking on the status of the project that is in progress.

Is the reactor module integration with Spring Kafka in progress ? When can we expect this to be released.

Thanks in Advance !

**Comment by artembilan** [comment] 2018-02-27 22:26
Duplicate of #43.

You can find all the related info there and in the associated Pull Request #559

Unfortunately we don't have now resources to jump to this subject and even review that PR.

We might come back to the story somewhere in the next version.

Meanwhile you can check how I use Reactor Kafka together with Spring Integration: https://github.com/artembilan/spring-integration-s1p2017/blob/master/src/test/java/org/springoneplatform2017/integration/kafka/SpringIntegrationS1p2017KafkaTests.java#L82.

Not sure though what else, you people would like to see from Spring support perspective...

**Closed by artembilan** 2018-02-27 22:26 UTC
