### ISSUE TITLE
CommonDelegatingErrorHandler does not update the classifier on "addDelegate" method

### ISSUE THREAD

**Issue by YosiBronsberg** [spring-projects/spring-kafka#3100] opened 2024-03-05 09:49 UTC
Spring Kafka version: 2.8.11

**Describe the bug**

When using the "addDelegate" method on a "CommonDelegatingErrorHandler" the handler does not update the BinaryExceptionClassifier to classify the newly added exception (as it does in the "setErrorHandlers" method). 
As a result, when an exception of the given type is thrown in the container, the classifier fails to classify it, and no delegate is found.

**To Reproduce**

1. Create a new instance of CommonDelegatingErrorHandler with a default error handler.
2. Add a delegate for a specific exception using the "addDelegate" method.
3. Cause the consumer to throw this exception, given that the thrown exception has a cause (otherwise, it will succeed only because the error handler returns the root cause by default).
4. Exception is not classified, so the expected delegate is not executed.

**Expected behavior**

The classifier should be updated with the given exception class when adding a new delegate.

**Comment by artembilan** [comment] 2024-03-05 14:17
Duplicate of https://github.com/spring-projects/spring-kafka/issues/2826.

Please, consider to upgrade to more fresh Spring for Apache Kafka version.

**Closed by artembilan** 2024-03-05 14:17 UTC
Labels: status: duplicate

**Comment by YosiBronsberg** [comment] 2024-03-05 14:24
Thank you @artembilan!
