### ISSUE TITLE
Enforcing container to stop on transaction fencing

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#1612] opened 2020-11-09 10:09 UTC
**Affects Version(s):** 2.5.6.RELEASE

Regarding this stackoverflow question :
https://stackoverflow.com/questions/64665725/why-i-lost-messages-when-using-kafka-with-eos-beta/64665928

When a ProducerFencedException | FencedInstanceIdException occurs, the framework assumes that the consumer will stop, and thus is just logging : 
https://github.com/spring-projects/spring-kafka/blob/fb1977c14cd72030828256ec7b7750d0fc85442a/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1519-L1523

It would be usefull to have a safeguard , enforcing the consumer container to stop to prevent losing message in an unexpected behavior concerning this exception.

**Comment by garyrussell** [comment] 2020-11-09 15:37
The consumer cannot tell if the fenced exception is caused by a rebalance or timeout. This is a known limitation of Kafka itself, and will be addressed in a future release.

We can certainly add an option to stop the container on these exceptions, but the proper fix can only be done when the new exception is thrown for a timeout.

https://issues.apache.org/jira/browse/KAFKA-9803

**Comment by garyrussell** [comment] 2020-11-09 15:50
In the meantime, you should make sure the `transaction.timeout.ms` is long enough to process a batch of records without timing out.

**Comment by Rajh** [comment] 2020-11-09 15:53
Reading https://issues.apache.org/jira/browse/KAFKA-9803 I can see :

> Currently the coordinator does not distinguish these two cases. Both will end up as a `ProducerFencedException`, which means the producer needs to shut itself down.

Actually the producer is not shutting down, is it ? Or if it is, what happens to the container ? Since it is not rollbacking, does it try to re produce the message and then the ProducerFactory creates a new one ?

**Comment by garyrussell** [comment] 2020-11-09 17:46
The producer factory should recycle the producer (it does for me with your test application with the short tx timeout). Any error on `begin/abort/commitTransaction()` closes the producer and a new one is created.

**Comment by Rajh** [comment] 2020-11-09 18:46
Yes but since the exception is ignored the consumer skip the messages with the failed producer and continues with a new batch with a new producer.

**Comment by garyrussell** [comment] 2020-11-09 18:47
Right, so until they fix it, the only thing we can do is stop the container.

Here's another work-around:

Set the container's `idleEventInterval`. Add an event listener to catch `ListenerContainerIdleEvent`; then perform a dummy (no-op) transaction; e.g. once a day.

**Comment by Rajh** [comment] 2020-11-09 18:57
Which kind of no-op can be done to keep a transaction up ? (without producing a message :D)

**Comment by garyrussell** [comment] 2020-11-09 19:13
```java
template.executeInTransaction(t -> {
      return null;
});
```

It will just do `beginTransaction(), commitTransaction()`.

**Comment by Rajh** [comment] 2020-11-10 08:10
Does handling ```ContainerStoppedEvent``` in order to restart the container can have side effects ?

Say we have 3 instances of the application running on a topic with 3 partitions (1 partition for each consumer).
When a consumer transaction timeout, the container is stopped, this will start a rebalance for the others.
Then the container is restarted, and it will start a new rebalance.

Does those rebalances can trigger a ```ProducerFencedException``` but this time due to a rebalance and not a transaction timeout ?
And if this is the case, does restarting everytime can cause a sort of dead lock, or disturb the rebalances ?

**Comment by garyrussell** [comment] 2020-11-10 14:12
Yes, it will cause a rebalance, although that can be avoided by setting a unique `ConsumerConfig.GROUP_INSTANCE_ID_CONFIG` on each instance (using [static membership](https://kafka.apache.org/documentation/#static_membership)).

**Comment by Rajh** [comment] 2020-11-10 14:31
We are using dynamic auto scaling. This means our consumer partitions are not static.

Causing a rebalance does not really matters, this FencedException should be rare and causing a rebalance to recover is acceptable.
My concern was more about the dead lock having rebalance causing FencedException causing rebalance, etc ...

**Comment by garyrussell** [comment] 2020-11-10 14:44
It won't deadlock, even if the other instances are not well-behaved (if they don't handle the rebalance in a timely manner).

**Closed** 2020-11-10 17:47 UTC
Labels: backport 2.5.x, type: improvement

**Comment by c0ldd** [comment] 2026-04-16 14:49
I have to continue the discussion in this thread, since using this feature was supposed to prevent message loss, but practice has shown that we continue to lose them.
Affects Version(s): 3.3.14.RELEASE
Consuming multiple topics by pattern. ContainerFactory settings looks like this:
```
ConcurrentKafkaListenerContainerFactory<ByteArray, ByteArray>().apply {
                    consumerFactory = ref()
                    isBatchListener = true
                    containerProperties.kafkaAwareTransactionManager = ref()
                    // to optimize DB fetch mechanics by importing one entity type per batch
                    containerProperties.subBatchPerPartition = true
                    val executor = SimpleAsyncTaskScheduler()
                    executor.setThreadNamePrefix("kafka-ext-")
                    executor.setVirtualThreads(true)
                    containerProperties.listenerTaskExecutor = executor
                    containerProperties.scheduler = executor
                    val syncConfig = ref<ExternalSyncConfig>()
                    setConcurrency(syncConfig.parallelism)
                    containerProperties.isStopContainerWhenFenced = true
                    setContainerCustomizer {
                        // gives better distribution for not know before start partition list
                        // can be removed when migrate to consumer per topic mode
                        it.containerProperties.kafkaConsumerProperties[PARTITION_ASSIGNMENT_STRATEGY_CONFIG] =
                            CooperativeStickyAssignor::class.java.name + "," + RoundRobinAssignor::class.java.name
                        it.containerProperties.kafkaConsumerProperties.putAll(syncConfig.consumerProperties)
                    }
                }
```
Idea was to receive event when consumer is stopped and then restart it like this:
```
override fun onApplicationEvent(event: ConsumerStoppedEvent) {
        val container = event.source
        if (event.reason == ConsumerStoppedEvent.Reason.FENCED && container is KafkaMessageListenerContainer<*, *>) {
            log.warn { "Restart consumer after stopped on fenced exception" }
            try {
                container.start()
            } catch (e: Exception) {
                log.error(e) { "Failed to restart consumer" }
            }
        }
    }
```
Logs are pretty fine, we see successfully restarted and working consumer, but stored data is inconsistent shows losing messages. 
Maybe we missing some configurations. Any advice will help !

**Comment by sobychacko** [comment] 2026-04-16 15:10
@c0ldd Ok, we will take a look at this soon. Thanks!

**Comment by c0ldd** [comment] 2026-04-16 15:46
@sobychacko  can we suspend this ? I suddenly realized that perhaps we are interpreting data consistency incorrectly. I'll collect more data for this issue and will return. Sorry for jumping to conclusions
