### ISSUE TITLE
Failed to construct a kafka producer when it tries to serialize a data class using JsonSerializer

### ISSUE THREAD

**Issue by douglas-DS** [spring-projects/spring-kafka#1885] opened 2021-07-24 17:28 UTC
**Affects Version(s):** 2.5.3

When a producer tries to serialize a value(data class) the application raises a `org.apache.kafka.common.KafkaException` caused by `java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JavaType`

The producer `value-serializer` was configured to use the `org.springframework.kafka.support.serializer.JsonSerializer` class.

It's how my current yaml file looks like:

```
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
```

**Workaround**

To solve this problem i had to put an explicit dependency declaration for `jackson-databind`, as shown below:
```
implementation("com.fasterxml.jackson.core:jackson-databind")
```

**Comment by artembilan** [comment] 2021-07-24 22:13
That’s correct : Jackson is optional in Spring for Apache Kafka artifacts. Just because not everyone deals with JSON (Let’s say Avro), so it is going to be extra noise for them to have unexpected Jackson dependency in their class path. Therefore if your request to make Jackson as hard dependency in this project, then I’m afraid we will reject it and close as `Works as Designed`.

**Comment by douglas-DS** [comment] 2021-07-26 02:20
I didn't know about that, since i came from another framework extensions for kafka that handle JSON without any additional dependencies. But it's ok i can deal with one more dependency or a custom converter for my data classes.

Appreciate your time and help.

**Comment by artembilan** [comment] 2021-07-26 13:13
Good. Glad you can deal with optional dependency.
Closing as `Works as Designed`

**Closed by artembilan** 2021-07-26 13:13 UTC
