### ISSUE TITLE
EmbeddedKafka startup fails after updated to spring-kafka 2.8.2 from 2.8.1

### ISSUE THREAD

**Issue by berniPLN** [spring-projects/spring-kafka#2097] opened 2022-02-08 17:35 UTC
After upgrading from spring-boot 2.5.8 with spring-kafka 2.8.1 to spring-boot 2.6.3 which includes spring-kafka 2.8.2 I got
an AccessDeniedException:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: C:\Users\LOCAL_~1.PLU\Temp\spring.kafka.aa7b5128-8b4a-48b5-bbb5-83d7d4366ff019355599263815032

Fixing spring-kafka version to 2.8.1 does not shows this issue, so probably there might be a bug in spring-kafka 2.8.2 connected to the use of kafka 3.0.0 like in: https://github.com/spring-projects/spring-kafka/issues/2018 and https://issues.apache.org/jira/browse/KAFKA-13391

**Comment by garyrussell** [comment] 2022-02-08 17:45
This is a known issue with kafka 3.0.0 used by spring-kafka 2.8.x (when you were using Boot 2.5.x, it downgraded the kafka jars to 2.7.x).

It is the change to the Boot version that exposes this problem.

See the documentation for the work around: https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps

Duplicate of https://github.com/spring-projects/spring-kafka/issues/2018

**Closed by garyrussell** 2022-02-08 17:45 UTC

**Comment by garyrussell** [comment] 2022-02-08 17:47
When spring-kafka 2.8.3 is released, you can upgrade the kafka jars to 3.1.0.

**Comment by huazailmh** [comment] 2022-02-09 07:04
> When spring-kafka 2.8.3 is released, you can upgrade the kafka jars to 3.1.0.
> 
> 3.0.1 is scheduled for March, which will be too late for s-k 2.8.3.

Hi @garyrussell , thanks for the info. May I know what is the release plan for spring-kafka 2.8.3 (I mean when would it be released)?

Thanks and BR,
Bruce.

**Comment by garyrussell** [comment] 2022-02-09 13:42
The 3.0.1 Kafka jars are planned for March (see their release plan); the first 2.8.x version after that release will move to 3.0.1.

https://cwiki.apache.org/confluence/display/KAFKA/Future+release+plan

spring-kafka 2.8.3 is currently scheduled for Feb 21 (with a patch to make it compatible with the 3.1.0 embedded broker).

https://github.com/spring-projects/spring-kafka/milestones
